# Generated by Django 3.0.4 on 2020-05-19 15:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=8,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for decision"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WorkBasket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("NEW_IN_PROGRESS", "New In Progress"),
                            ("EDITING", "Editing"),
                            ("AWAITING_APPROVAL", "Awaiting Approval"),
                            ("APPROVAL_REJECTED", "Approval Rejected"),
                            ("READY_FOR_EXPORT", "Ready For Export"),
                            (
                                "AWAITING_CDS_UPLOAD_CREATE_NEW",
                                "Awaiting Cds Upload Create New",
                            ),
                            ("AWAITING_CDS_UPLOAD_EDIT", "Awaiting Cds Upload Edit"),
                            (
                                "AWAITING_CDS_UPLOAD_OVERWRITE",
                                "Awaiting Cds Upload Overwrite",
                            ),
                            (
                                "AWAITING_CDS_UPLOAD_DELETE",
                                "Awaiting Cds Upload Delete",
                            ),
                            ("SENT_TO_CDS", "Sent To Cds"),
                            ("SENT_TO_CDS_DELETE", "Sent To Cds Delete"),
                            ("PUBLISHED", "Published"),
                            ("CDS_ERROR", "Cds Error"),
                        ],
                        default="NEW_IN_PROGRESS",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the changes to the tariff"
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workbaskets.ApprovalDecision",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WorkBasketItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("diff", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("draft", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "errors",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "workbasket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workbaskets.WorkBasket",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
