# Generated by Django 3.0.11 on 2020-11-18 18:56
import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workbasket",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("NEW_IN_PROGRESS", "New - in progress"),
                    ("EDITING", "Editing"),
                    ("AWAITING_APPROVAL", "Awaiting approval"),
                    ("APPROVAL_REJECTED", "Failed approval"),
                    ("READY_FOR_EXPORT", "Ready for export"),
                    (
                        "AWAITING_CDS_UPLOAD_CREATE_NEW",
                        "Awaiting CDS upload - create new",
                    ),
                    ("AWAITING_CDS_UPLOAD_EDIT", "Awaiting CDS upload - edit"),
                    (
                        "AWAITING_CDS_UPLOAD_OVERWRITE",
                        "Awaiting CDS upload - overwrite",
                    ),
                    ("AWAITING_CDS_UPLOAD_DELETE", "Awaiting CDS upload - delete"),
                    ("SENT_TO_CDS", "Sent to CDS"),
                    ("SENT_TO_CDS_DELETE", "Sent to CDS - delete"),
                    ("PUBLISHED", "Published"),
                    ("CDS_ERROR", "CDS error"),
                ],
                db_index=True,
                default="NEW_IN_PROGRESS",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workbasket",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Short name for this workbasket",
                max_length=255,
            ),
        ),
    ]
