# Generated by Django 3.1 on 2020-12-26 10:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
