# Generated by Django 3.0.10 on 2020-11-19 12:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
