# Generated by Django 3.1.12 on 2021-09-21 14:10

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        # AddField operations for approver and author fields have been moved here from workbaskets.0001_initial to resolve a circular dependency issue with common.0001_initial following a change mid-project to a custom user model.
        migrations.AddField(
            model_name="workbasket",
            name="approver",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_workbaskets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workbasket",
            name="author",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workbasket",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("EDITING", "Editing"),
                    ("PROPOSED", "Proposed"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("PUBLISHED", "Published"),
                    ("ERRORED", "Errored"),
                ],
                db_index=True,
                default="EDITING",
                editable=False,
                max_length=50,
            ),
        ),
    ]
