# Generated by Django 3.1 on 2020-12-09 14:07
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0002_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="workbasket",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="workbaskets.workbasket",
            ),
        ),
    ]
