# Generated by Django 3.0.10 on 2020-11-27 17:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201127_1737"),
        ("workbaskets", "0002_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkBasketTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.Transaction",
                    ),
                ),
                (
                    "workbasket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workbaskets.WorkBasket",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workbasket",
            name="transactions",
            field=models.ManyToManyField(
                related_name="workbaskets",
                through="workbaskets.WorkBasketTransaction",
                to="common.Transaction",
            ),
        ),
    ]
