# Generated by Django 3.1 on 2020-12-10 11:25
from django.db import migrations
from django.db import models
from django.db.models import F


def add_transaction_key(apps, schema_editor):
    Transaction = apps.get_model("workbaskets", "Transaction")

    Transaction.objects.all().update(composite_key=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0003_auto_20201209_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="composite_key",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.RunPython(add_transaction_key),
        migrations.AlterField(
            model_name="transaction",
            name="composite_key",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
