# Generated by Django 3.1 on 2021-01-02 08:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0003_auto_20201228_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workbasket",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Short name for this workbasket",
                max_length=255,
                unique=True,
            ),
        ),
    ]
