# Generated by Django 3.1.14 on 2022-09-01 17:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0004_archive_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbasket",
            name="rule_check_task_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
