# Generated by Django 3.2.18 on 2023-03-15 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0006_auto_20221220_1532"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workbasket",
            options={
                "verbose_name": "workbasket",
                "verbose_name_plural": "workbaskets",
            },
        ),
    ]
