# Generated by Django 4.2.16 on 2024-12-12 15:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0008_datarow_dataupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbasket",
            name="missing_measures_check_task_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
