# Generated by Django 4.2.20 on 2025-04-02 12:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_tasktemplate_automation_class_name_automation"),
        ("workbaskets", "0009_workbasket_missing_measures_check_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateWorkBasketAutomation",
            fields=[
                (
                    "automation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.automation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tasks.automation",),
        ),
        migrations.CreateModel(
            name="EndDateMeasuresAutomation",
            fields=[
                (
                    "automation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.automation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tasks.automation",),
        ),
        migrations.CreateModel(
            name="RunRuleChecksAutomation",
            fields=[
                (
                    "automation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.automation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tasks.automation",),
        ),
    ]
