# Generated by Django 4.2.18 on 2025-03-04 17:31

from django.db import migrations


def forwards_move_assignments_and_comments(apps, schema_editor):
    """
    Forward migration operation:
    1. Move UserAssignment instances with their associated Task data
       (i.e. WorkBasket) from the tasks package to instances of their new,
       simplified equivalent workbaskets.models.WorkBasketAssignment.
    2. Move Comment instances with their associated Task data
       (i.e. WorkBasket) from the tasks package to instances of their new,
       simplified equivalent workbaskets.models.WorkBasketComment.

    Notes:
       This migration moves both task.models.UserAssignment and
       task.models.Comment instances because they both reference instances of
       the task.models.Task, which must all be cleaned up / deleted. Other
       approaches are possible, decomposing the two, but the current approach
       has the benefit of cleaning Task instances in a single, relatively
       simple atomic operation.
    """

    Comment = apps.get_model("tasks", "Comment")
    UserAssignment = apps.get_model("tasks", "UserAssignment")
    Task = apps.get_model("tasks", "Task")
    WorkBasketAssignment = apps.get_model("workbaskets", "WorkBasketAssignment")
    WorkBasketComment = apps.get_model("workbaskets", "WorkBasketComment")

    user_assignments_qs = UserAssignment.objects.all()
    for user_assignment in user_assignments_qs:
        WorkBasketAssignment.objects.create(
            # created_at is an auto_now_add field so can't be copied.
            # updated_at is an auto_now field so can't be copied.
            workbasket=user_assignment.task.workbasket,
            user=user_assignment.user,
            assigned_by=user_assignment.assigned_by,
            assignment_type=user_assignment.assignment_type,
            unassigned_at=user_assignment.unassigned_at,
        )

    comments_qs = Comment.objects.all()
    for comment in comments_qs:
        WorkBasketComment.objects.create(
            # created_at is an auto_now_add field so can't be copied.
            # updated_at is an auto_now field so can't be copied.
            author=comment.author,
            content=comment.content,
            workbasket=comment.task.workbasket,
        )

    tasks_qs = Task.objects.all()

    tasks_qs.delete()
    user_assignments_qs.delete()
    comments_qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0010_workbasketcomment_workbasketassignment"),
        ("tasks", "0002_comment"),
    ]

    operations = [
        migrations.RunPython(forwards_move_assignments_and_comments),
    ]
