# Generated by Django 4.2.20 on 2025-03-18 15:15

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0011_move_assignments_and_comments_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workbasketassignment",
            name="workbasket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workbaskets.workbasket",
            ),
        ),
    ]
