# Generated by Django 4.2.18 on 2025-04-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workbaskets",
            "0013_createworkbasketautomation_enddatemeasuresautomation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runrulechecksautomation",
            name="automation_ptr",
        ),
        migrations.DeleteModel(
            name="EndDateMeasuresAutomation",
        ),
        migrations.DeleteModel(
            name="RunRuleChecksAutomation",
        ),
    ]
