# Generated by Django 3.0.10 on 2020-11-13 17:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hmrc_sdes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Upload",
        ),
    ]
