# Generated by Django 3.0.8 on 2020-07-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0002_add_goods_nomenclature"),
        ("measures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="commodity_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="measures",
                to="commodities.GoodsNomenclature",
            ),
        ),
    ]
