# Generated by Django 3.1 on 2021-01-06 15:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("footnotes", "0001_initial"),
        ("regulations", "0001_initial"),
        ("measures", "0001_initial"),
        ("additional_codes", "0001_initial"),
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="order_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="quotas.quotaordernumber",
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="terminating_regulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terminated_measures",
                to="regulations.regulation",
            ),
        ),
        migrations.AddField(
            model_name="footnoteassociationmeasure",
            name="associated_footnote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="footnotes.footnote",
            ),
        ),
        migrations.AddField(
            model_name="footnoteassociationmeasure",
            name="footnoted_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.measure",
            ),
        ),
        migrations.AddField(
            model_name="additionalcodetypemeasuretype",
            name="additional_code_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="additional_codes.additionalcodetype",
            ),
        ),
        migrations.AddField(
            model_name="additionalcodetypemeasuretype",
            name="measure_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.measuretype",
            ),
        ),
    ]
