# Generated by Django 3.1 on 2021-02-01 16:39
from django.db import migrations

from common.migration_operations import ConvertTaricDateRange


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0002_auto_20210106_1533"),
    ]

    operations = [
        ConvertTaricDateRange("additionalcodetypemeasuretype", "valid_between"),
        ConvertTaricDateRange("dutyexpression", "valid_between"),
        ConvertTaricDateRange("measure", "valid_between"),
        ConvertTaricDateRange("measureaction", "valid_between"),
        ConvertTaricDateRange("measureconditioncode", "valid_between"),
        ConvertTaricDateRange("measurement", "valid_between"),
        ConvertTaricDateRange("measurementunit", "valid_between"),
        ConvertTaricDateRange("measurementunitqualifier", "valid_between"),
        ConvertTaricDateRange("measuretype", "valid_between"),
        ConvertTaricDateRange("measuretypeseries", "valid_between"),
        ConvertTaricDateRange("monetaryunit", "valid_between"),
    ]
