# Generated by Django 3.0.10 on 2020-09-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0003_add_measures_data_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyexpression",
            name="prefix",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="measurementunit",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="measurementunitqualifier",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
