# Generated by Django 3.1 on 2021-02-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0004_rename_condition_component_measurement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurecondition",
            options={"ordering": ["component_sequence_number"]},
        ),
    ]
