# Generated by Django 3.0.10 on 2020-09-20 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0004_add_prefix_and_abbreviations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyexpression",
            name="sid",
            field=models.IntegerField(
                choices=[
                    (1, "% or amount"),
                    (2, "minus\xa0% or amount"),
                    (3, "The rate is replaced by the levy"),
                    (4, "+\xa0% or amount"),
                    (5, "The rate is replaced by the reduced levy"),
                    (6, "+ Suplementary amount"),
                    (7, "+ Levy"),
                    (9, "+ Reduced levy"),
                    (11, "+ Variable component"),
                    (12, "+ agricultural component"),
                    (13, "+ Reduced variable component"),
                    (14, "+ reduced agricultural component"),
                    (15, "Minimum"),
                    (17, "Maximum"),
                    (19, "+\xa0% or amount"),
                    (20, "+\xa0% or amount"),
                    (21, "+ additional duty on sugar"),
                    (23, "+ 2\xa0% Additional duty on sugar"),
                    (25, "+ reduced additional duty on sugar"),
                    (27, "+ additional duty on flour"),
                    (29, "+ reduced additional duty on flour"),
                    (31, "Accession compensatory amount"),
                    (33, "+ Accession compensatory amount"),
                    (35, "Maximum"),
                    (36, "minus\xa0% CIF"),
                    (37, "(nothing)"),
                    (40, "Export refunds for cereals"),
                    (41, "Export refunds for rice"),
                    (42, "Export refunds for eggs"),
                    (43, "Export refunds for sugar"),
                    (44, "Export refunds for milk products"),
                    (99, "Supplementary unit"),
                ]
            ),
        ),
    ]
