# Generated by Django 3.0.10 on 2020-09-21 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0005_numeric_id_for_duty_expression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementunit",
            name="code",
            field=models.CharField(
                max_length=3,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]{3}$")],
            ),
        ),
    ]
