# Generated by Django 3.1 on 2021-02-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0005_auto_20210224_2242"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurecondition",
            options={
                "ordering": [
                    "dependent_measure__sid",
                    "condition_code__code",
                    "component_sequence_number",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="measureconditioncomponent",
            options={"ordering": ["condition__sid", "duty_expression__sid"]},
        ),
    ]
