# Generated by Django 3.0.10 on 2020-09-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0006_include_national_measurement_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="measurement_unit_qualifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.MeasurementUnitQualifier",
            ),
        ),
    ]
