# Generated by Django 3.1 on 2021-02-25 16:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0006_auto_20210225_1603"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 44;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 99;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 43;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 13;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 31;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 40;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 41;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 11;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 33;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 6;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 5;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 7;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 42;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 23;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 9;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 1;
UPDATE measures_dutyexpression SET prefix='-' WHERE sid = 2;
UPDATE measures_dutyexpression SET prefix='' WHERE sid = 3;
UPDATE measures_dutyexpression SET prefix='+' WHERE sid = 4;
UPDATE measures_dutyexpression SET prefix='+ AC' WHERE sid = 12;
UPDATE measures_dutyexpression SET prefix='+ AC (reduced)' WHERE sid = 14;
UPDATE measures_dutyexpression SET prefix='MIN' WHERE sid = 15;
UPDATE measures_dutyexpression SET prefix='MAX' WHERE sid = 17;
UPDATE measures_dutyexpression SET prefix='+' WHERE sid = 19;
UPDATE measures_dutyexpression SET prefix='+' WHERE sid = 20;
UPDATE measures_dutyexpression SET prefix='+ SD' WHERE sid = 21;
UPDATE measures_dutyexpression SET prefix='+ SD (reduced)' WHERE sid = 25;
UPDATE measures_dutyexpression SET prefix='+ FD' WHERE sid = 27;
UPDATE measures_dutyexpression SET prefix='+ FD (reduced)' WHERE sid = 29;
UPDATE measures_dutyexpression SET prefix='MAX' WHERE sid = 35;
UPDATE measures_dutyexpression SET prefix='MIN' WHERE sid = 36;
UPDATE measures_dutyexpression SET prefix='NIHIL' WHERE sid = 37;
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'GRT';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'KAC';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'MPR';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'WAT';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'KMT';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'EUR';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'KCC';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'DHS';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'KCL';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'MGM';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'MCG';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'MLT';
UPDATE measures_measurementunit SET abbreviation='' WHERE code = 'MCL';
UPDATE measures_measurementunit SET abbreviation='TJ' WHERE code = 'TJO';
UPDATE measures_measurementunit SET abbreviation='p/st' WHERE code = 'NAR';
UPDATE measures_measurementunit SET abbreviation='1,000 kWh' WHERE code = 'MWH';
UPDATE measures_measurementunit SET abbreviation='1,000 p/st' WHERE code = 'MIL';
UPDATE measures_measurementunit SET abbreviation='kg' WHERE code = 'KGM';
UPDATE measures_measurementunit SET abbreviation='m' WHERE code = 'MTR';
UPDATE measures_measurementunit SET abbreviation='1,000 kg' WHERE code = 'TNE';
UPDATE measures_measurementunit SET abbreviation='kg N' WHERE code = 'KNI';
UPDATE measures_measurementunit SET abbreviation='gi F/S' WHERE code = 'GFI';
UPDATE measures_measurementunit SET abbreviation='kg met.am.' WHERE code = 'KMA';
UPDATE measures_measurementunit SET abbreviation='l alc. 100%' WHERE code = 'LPA';
UPDATE measures_measurementunit SET abbreviation='m2' WHERE code = 'MTK';
UPDATE measures_measurementunit SET abbreviation='hl' WHERE code = 'HLT';
UPDATE measures_measurementunit SET abbreviation='kg U' WHERE code = 'KUR';
UPDATE measures_measurementunit SET abbreviation='ce/el' WHERE code = 'NCL';
UPDATE measures_measurementunit SET abbreviation='1,000 l' WHERE code = 'KLT';
UPDATE measures_measurementunit SET abbreviation='pa' WHERE code = 'NPR';
UPDATE measures_measurementunit SET abbreviation='kg K2O' WHERE code = 'KPO';
UPDATE measures_measurementunit SET abbreviation='10,000 kg/polar' WHERE code = 'DAP';
UPDATE measures_measurementunit SET abbreviation='kg KOH' WHERE code = 'KPH';
UPDATE measures_measurementunit SET abbreviation='kg 90 % sdt' WHERE code = 'KSD';
UPDATE measures_measurementunit SET abbreviation='100 m' WHERE code = 'HMT';
UPDATE measures_measurementunit SET abbreviation='100 p/st' WHERE code = 'CEN';
UPDATE measures_measurementunit SET abbreviation='100 kg' WHERE code = 'DTN';
UPDATE measures_measurementunit SET abbreviation='g' WHERE code = 'GRM';
UPDATE measures_measurementunit SET abbreviation='c/k' WHERE code = 'CTM';
UPDATE measures_measurementunit SET abbreviation='ct/l' WHERE code = 'CCT';
UPDATE measures_measurementunit SET abbreviation='kg P2O5' WHERE code = 'KPP';
UPDATE measures_measurementunit SET abbreviation='m3' WHERE code = 'MTQ';
UPDATE measures_measurementunit SET abbreviation='% vol' WHERE code = 'ASV';
UPDATE measures_measurementunit SET abbreviation='kg H2O2' WHERE code = 'KNS';
UPDATE measures_measurementunit SET abbreviation='kg NaOH' WHERE code = 'KSH';
UPDATE measures_measurementunit SET abbreviation='l' WHERE code = 'LTR';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'H';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'N';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'B';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'J';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'F';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'L';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'D';
UPDATE measures_measurementunitqualifier SET abbreviation='' WHERE code = 'K';
UPDATE measures_measurementunitqualifier SET abbreviation='lactic matter' WHERE code = 'P';
UPDATE measures_measurementunitqualifier SET abbreviation='dry lactic matter' WHERE code = 'T';
UPDATE measures_measurementunitqualifier SET abbreviation='net drained wt' WHERE code = 'E';
UPDATE measures_measurementunitqualifier SET abbreviation='tot alc' WHERE code = 'A';
UPDATE measures_measurementunitqualifier SET abbreviation='std qual' WHERE code = 'R';
UPDATE measures_measurementunitqualifier SET abbreviation='1 000' WHERE code = 'C';
UPDATE measures_measurementunitqualifier SET abbreviation='net dry' WHERE code = 'M';
UPDATE measures_measurementunitqualifier SET abbreviation='% sacchar.' WHERE code = 'Z';
UPDATE measures_measurementunitqualifier SET abbreviation='hl' WHERE code = 'X';
UPDATE measures_measurementunitqualifier SET abbreviation='of biodiesel content' WHERE code = 'I';
UPDATE measures_measurementunitqualifier SET abbreviation='raw sugar' WHERE code = 'S';
UPDATE measures_measurementunitqualifier SET abbreviation='gross' WHERE code = 'G';
            """,
        ),
    ]
