# Generated by Django 3.0.10 on 2020-09-21 14:38
import django.db.models.deletion
from django.db import migrations
from django.db import models


def copy_trade_movement_code(apps, schema_editor):
    MeasureType = apps.get_model("measures", "MeasureType")
    for measure_type in MeasureType.objects.all().iterator():
        if measure_type.sid in [
            "CEX",
            "COE",
            "ECM",
            "EHC",
            "EQC",
            "EWP",
            "PRE",
        ]:
            measure_type.origin_destination_code = 0
        else:
            measure_type.origin_destination_code = measure_type.trade_movement_code
        measure_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0006_include_national_measurement_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="measurement_unit_qualifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.MeasurementUnitQualifier",
            ),
        ),
        migrations.AddField(
            model_name="measuretype",
            name="origin_destination_code",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Import"), (1, "Export"), (2, "Import/Export")], null=True
            ),
        ),
        migrations.RunPython(
            code=copy_trade_movement_code,
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="origin_destination_code",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Import"), (1, "Export"), (2, "Import/Export")]
            ),
        ),
    ]
