# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0007_optional_measurement_unit_and_origin_dest_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="export_refund_nomenclature_sid",
            field=common.fields.SignedIntSID(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="measure",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="measurecondition",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
    ]
