# Generated by Django 3.1.12 on 2021-06-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0007_add_duty_expression_prefixes_and_measurement_unit_abbrevs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measureaction",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="measureconditioncode",
            options={"ordering": ["code"]},
        ),
    ]
