# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0008_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcodetypemeasuretype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="dutyexpression",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measure",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measureaction",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measureconditioncode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurementunit",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurementunitqualifier",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measuretypeseries",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="monetaryunit",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
