# Generated by Django 3.1.13 on 2021-10-22 12:20

from django.db import migrations


def forwards(apps, schema_editor):
    MeasurementUnitQualifier = apps.get_model("measures", "MeasurementUnitQualifier")
    # Originally this used MeasurementUnitQualifier.objects.filter(code="N").first()
    # but this tries to access valid_between which may not be created yet and then things
    # break.
    MeasurementUnitQualifier.objects.filter(code="N").update(abbreviation="net")


def backwards(app, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0008_auto_20210628_1641"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
