# Generated by Django 3.1 on 2020-12-26 16:38
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0009_auto_20201226_1638"),
        ("geo_areas", "0008_auto_20201226_1001"),
        ("measures", "0008_auto_20201027_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="footnotes",
            field=models.ManyToManyField(
                through="measures.FootnoteAssociationMeasure", to="footnotes.Footnote"
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="geographical_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="measures",
                to="geo_areas.geographicalarea",
            ),
        ),
        migrations.AlterField(
            model_name="measurecomponent",
            name="component_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to="measures.measure",
            ),
        ),
        migrations.AlterField(
            model_name="measurecondition",
            name="condition_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditions",
                to="measures.measureconditioncode",
            ),
        ),
        migrations.AlterField(
            model_name="measurecondition",
            name="dependent_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditions",
                to="measures.measure",
            ),
        ),
        migrations.AlterField(
            model_name="measureexcludedgeographicalarea",
            name="modified_measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exclusions",
                to="measures.measure",
            ),
        ),
    ]
