# Generated by Django 3.1.14 on 2022-03-10 10:30

from django.db import migrations, models


CERTIFICATE_ONLY_CODES = ["A", "B", "C", "H", "K", "P", "Q", "Y", "Z"]
PRICE_ONLY_CODES = ["F", "G", "L", "M", "N", "R", "S", "U", "V"]
CERTIFICATE_AND_PRICE_CODES = ["E", "I"]

REQUIRES_DUTY_CODES = ["01", "02", "03", "11", "12", "13", "15", "36"]


def forwards(apps, schema_editor):
    MeasureConditionCode = apps.get_model("measures", "MeasureConditionCode")
    MeasureAction = apps.get_model("measures", "MeasureAction")
    
    codes = MeasureConditionCode.objects.all()
    for code in codes:
        if code.code in CERTIFICATE_ONLY_CODES:
            code.accepts_certificate = True
            code.accepts_price = False
        
        if code.code in PRICE_ONLY_CODES:
            code.accepts_certificate = False
            code.accepts_price = True
        
        if code.code in CERTIFICATE_AND_PRICE_CODES:
            code.accepts_certificate = True
            code.accepts_price = True
        
        code.save()
    
    actions = MeasureAction.objects.all()
    for action in actions:
        if action.code in REQUIRES_DUTY_CODES:
            action.requires_duty = True
        else:
            action.requires_duty = False
        
        action.save()


def reverse(apps, schema_editor):
    MeasureConditionCode = apps.get_model("measures", "MeasureConditionCode")
    MeasureAction = apps.get_model("measures", "MeasureAction")
    
    codes = MeasureConditionCode.objects.all()
    for code in codes:
        code.accepts_certificate = False
        code.accepts_price = False
        code.save()
    
    actions = MeasureAction.objects.all()
    for action in actions:
        action.requires_duty = False
        action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0009_add_abbrev_to_unit_qualifier_with_code_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureaction',
            name='requires_duty',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='measureconditioncode',
            name='accepts_certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='measureconditioncode',
            name='accepts_price',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.AlterField(
            model_name='measureaction',
            name='requires_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measureconditioncode',
            name='accepts_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measureconditioncode',
            name='accepts_price',
            field=models.BooleanField(default=False),
        ),
    ]
