# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0009_auto_20201226_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcodetypemeasuretype",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="dutyexpression",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measure",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measureaction",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measureconditioncode",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurementunit",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measurementunitqualifier",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measuretype",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="measuretypeseries",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="monetaryunit",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
