# Generated by Django 3.1 on 2021-01-04 15:24
from django.db import migrations
from django.db import models

import measures.validators


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0009_auto_20201229_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measuretype",
            name="measure_explosion_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "Harmonised System Chapter"),
                    (4, "Harmonised System Heading"),
                    (6, "Harmonised System Subheading"),
                    (8, "Combined Nomenclature"),
                    (10, "TARIC"),
                ],
                validators=[measures.validators.validate_measure_explosion_level],
            ),
        ),
    ]
