# Generated by Django 3.1 on 2020-11-27 16:46
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0010_auto_20201118_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="dead_order_number",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[django.core.validators.RegexValidator("^[0-9]{6}$")],
            ),
        ),
    ]
