# Generated by Django 3.1 on 2020-12-01 10:30
import django.core.validators
from django.db import migrations
from django.db import models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0011_measure_dead_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="dead_order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=6,
                null=True,
                validators=[django.core.validators.RegexValidator("^[0-9]{6}$")],
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="reduction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[common.validators.NumberRangeValidator(1, 3)],
            ),
        ),
    ]
