# Generated by Django 3.1 on 2020-12-02 13:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0012_auto_20201201_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="dead_additional_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
