# Generated by Django 3.2.18 on 2023-03-28 14:11

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0012_add_back_three_missing_measures_already_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureActionPair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negative_action",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="negative_measure_action",
                        to="measures.measureaction",
                    ),
                ),
                (
                    "positive_action",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positive_measure_action",
                        to="measures.measureaction",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
