# Generated by Django 3.1 on 2020-12-03 14:53
from django.db import migrations
from django.db import models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0013_measure_dead_additional_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="reduction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[common.validators.NumberRangeValidator(1, 9)],
            ),
        ),
    ]
