# Generated by Django 3.2.20 on 2023-10-31 15:16

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0014_action_pair_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="dead_order_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=6,
                null=True,
                validators=[django.core.validators.RegexValidator("^05[0-9]{4}$")],
            ),
        ),
    ]
