# Generated by Django 3.1 on 2020-12-09 17:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0014_auto_20201203_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="dead_additional_code",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
