# Generated by Django 3.2.23 on 2023-12-13 15:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0015_alter_measure_dead_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateMeasures",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleaned_data", models.JSONField()),
            ],
        ),
    ]
