# Generated by Django 4.2.11 on 2024-03-27 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0016_measuresbulkcreator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measuresbulkcreator",
            name="current_transaction",
        ),
    ]
