# Generated by Django 3.2.23 on 2024-01-12 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0016_createmeasures"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreateMeasures",
            new_name="MeasuresBulkCreator",
        ),
    ]
