# Generated by Django 3.2.23 on 2024-01-24 15:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0018_auto_20240122_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="form_kwargs",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
