# Generated by Django 3.2.23 on 2024-02-15 16:15

import django.db.models.deletion
from django.db import migrations
from django.db import models

import measures.models.bulk_processing


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0008_datarow_dataupload"),
        ("common", "0010_set_tracked_model_datetime"),
        ("measures", "0019_measuresbulkcreator_form_kwargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="workbasket",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=measures.models.bulk_processing.REVOKE_TASKS_AND_SET_NULL,
                to="workbaskets.workbasket",
            ),
        ),
        migrations.AlterField(
            model_name="measuresbulkcreator",
            name="current_transaction",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=measures.models.bulk_processing.REVOKE_TASKS_AND_SET_NULL,
                related_name="measures_bulk_creators",
                to="common.transaction",
            ),
        ),
        migrations.CreateModel(
            name="BulkProcessorResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "created_transaction",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.transaction",
                    ),
                ),
            ],
            bases=(measures.models.bulk_processing.DateTimeStampedMixin, models.Model),
        ),
    ]
