# Generated by Django 3.2.23 on 2024-02-20 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models

import measures.models.bulk_processing


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0008_datarow_dataupload"),
        ("common", "0010_set_tracked_model_datetime"),
        ("measures", "0019_measuresbulkcreator_form_kwargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="task_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="workbasket",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=measures.models.bulk_processing.REVOKE_TASKS_AND_SET_NULL,
                to="workbaskets.workbasket",
            ),
        ),
        migrations.AlterField(
            model_name="measuresbulkcreator",
            name="current_transaction",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=measures.models.bulk_processing.REVOKE_TASKS_AND_SET_NULL,
                to="common.transaction",
            ),
        ),
        migrations.CreateModel(
            name="BulkProcessorResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "created_transaction",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="processing_result",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="measures.bulkprocessorresult",
            ),
        ),
    ]
