# Generated by Django 3.2.23 on 2024-02-28 16:57

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0020_auto_20240220_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="processing_state",
            field=django_fsm.FSMField(
                choices=[
                    ("AWAITING_PROCESSING", "Awaiting processing"),
                    ("CURRENTLY_PROCESSING", "Currently processing"),
                    ("SUCCESSFULLY_PROCESSED", "Successfully processed"),
                    ("FAILED_PROCESSING", "Failed processing"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="AWAITING_PROCESSING",
                editable=False,
                max_length=50,
                protected=True,
            ),
        ),
    ]
