# Generated by Django 3.2.23 on 2024-02-29 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0021_measuresbulkcreator_processing_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measuresbulkcreator",
            name="processing_result",
        ),
        migrations.DeleteModel(
            name="BulkProcessorResult",
        ),
    ]
