# Generated by Django 4.2.10 on 2024-03-01 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("measures", "0022_auto_20240229_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="user",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
