# Generated by Django 4.2.10 on 2024-03-18 14:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("measures", "0023_measuresbulkcreator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="measuresbulkcreator",
            name="successfully_processed_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
