# Generated by Django 3.0.7 on 2020-06-11 10:03
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("code", models.CharField(max_length=12)),
                ("description", models.TextField()),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("code", "=")],
                name="exclude_overlapping_commodities",
            ),
        ),
    ]
