# Generated by Django 3.0.6 on 2020-06-03 16:11

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('trackedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TrackedModel')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_between', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('code', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('version', models.PositiveIntegerField()),
            ],
            bases=('common.trackedmodel', models.Model),
        ),
        migrations.AddConstraint(
            model_name='commodity',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('valid_between', '&&'), ('code', '=')], name='exclude_overlapping_commodities'),
        ),
    ]
