# Generated by Django 3.1 on 2021-02-01 16:39
from django.db import migrations

from common.migration_operations import ConvertTaricDateRange


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        ConvertTaricDateRange("footnoteassociationgoodsnomenclature", "valid_between"),
        ConvertTaricDateRange("goodsnomenclature", "valid_between"),
        ConvertTaricDateRange("goodsnomenclaturedescription", "valid_between"),
        ConvertTaricDateRange("goodsnomenclatureindent", "valid_between"),
        ConvertTaricDateRange("goodsnomenclatureindentnode", "valid_between"),
    ]
