# Generated by Django 3.1 on 2021-02-18 11:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0002_auto_20210201_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="depth",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
