# Generated by Django 3.0.8 on 2020-07-17 14:39

import django.contrib.postgres.constraints
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_trackedmodel_update_type"),
        ("footnotes", "0002_refactor_footnotes"),
        ("measures", "0002_link_to_goods_nomenclature"),
        ("commodities", "0002_add_goods_nomenclature"),
    ]

    operations = [
        migrations.DeleteModel(name="Commodity",),
        migrations.AddField(
            model_name="goodsnomenclatureindent",
            name="indented_goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indents",
                to="commodities.GoodsNomenclature",
            ),
        ),
        migrations.AddField(
            model_name="goodsnomenclaturedescription",
            name="described_goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descriptions",
                to="commodities.GoodsNomenclature",
            ),
        ),
        migrations.AddField(
            model_name="goodsnomenclature",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="succeeding_goods",
                related_query_name="succeeding_goods",
                to="commodities.GoodsNomenclature",
            ),
        ),
        migrations.AddField(
            model_name="footnoteassociationgoodsnomenclature",
            name="associated_footnote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="footnotes.Footnote"
            ),
        ),
        migrations.AddField(
            model_name="footnoteassociationgoodsnomenclature",
            name="goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commodities.GoodsNomenclature",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsnomenclatureindent",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_goods_indents",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsnomenclaturedescription",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_goods_descriptions",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsnomenclature",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_goods",
            ),
        ),
    ]
