# Generated by Django 3.1.2 on 2020-10-16 11:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_refactor_update_type"),
        ("workbaskets", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("commodities", "0003_remove_commodities_and_add_relations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoodsNomenclatureIndent",
            new_name="GoodsNomenclatureIndentNode",
        ),
    ]
