# Generated by Django 3.1.6 on 2021-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0003_auto_20210218_1122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclaturedescription",
            options={"ordering": ("valid_between",)},
        ),
    ]
