# Generated by Django 3.1.2 on 2020-10-16 15:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0005_auto_20201016_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indented_goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indents",
                to="commodities.goodsnomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="indented_goods_nomenclature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="commodities.goodsnomenclature",
            ),
        ),
    ]
