# Generated by Django 3.1.2 on 2020-10-21 11:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0006_auto_20201016_1545"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsnomenclatureindentnode",
            name="indented_goods_nomenclature",
        ),
        migrations.RemoveField(
            model_name="goodsnomenclatureindentnode",
            name="sid",
        ),
        migrations.RemoveField(
            model_name="goodsnomenclatureindentnode",
            name="trackedmodel_ptr",
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="path",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
