# Generated by Django 3.1.12 on 2021-06-28 17:08

from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0007_validity_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="description",
            field=common.fields.LongDescription(),
        ),
    ]
