# Generated by Django 3.1.2 on 2020-10-22 10:47
import django.core.validators
from django.db import migrations
from django.db import models


def add_indents_indent(apps, schema_editor):
    GoodsNomenclatureIndent = apps.get_model("commodities", "GoodsNomenclatureIndent")

    for indent_obj in GoodsNomenclatureIndent.objects.all():
        depth = indent_obj.nodes.first().depth
        indent = str(0 if depth < 3 else depth - 2).zfill(2)
        indent_obj.indent = indent
        indent_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0007_auto_20201021_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.CharField(
                max_length=2,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.RunPython(add_indents_indent),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.CharField(
                max_length=2, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="item_id",
            field=models.CharField(
                db_index=True,
                max_length=10,
                validators=[django.core.validators.RegexValidator("\\d{10}")],
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="sid",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="suffix",
            field=models.CharField(
                db_index=True,
                max_length=2,
                validators=[django.core.validators.RegexValidator("\\d{2}")],
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="sid",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
    ]
