# Generated by Django 3.0.10 on 2020-10-23 15:06
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0008_goodsnomenclatureindent_indent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
