# Generated by Django 3.0.10 on 2020-11-08 13:03
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_refactor_update_type"),
        ("commodities", "0009_make_indent_numeric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsnomenclature",
            name="origin",
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureSuccessor",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "absorbed_into_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commodities.GoodsNomenclature",
                    ),
                ),
                (
                    "replaced_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor_links",
                        to="commodities.GoodsNomenclature",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel",),
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureOrigin",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "derived_from_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commodities.GoodsNomenclature",
                    ),
                ),
                (
                    "new_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_links",
                        to="commodities.GoodsNomenclature",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel",),
        ),
        migrations.AddField(
            model_name="goodsnomenclature",
            name="origins",
            field=models.ManyToManyField(
                related_name="_goodsnomenclature_origins_+",
                through="commodities.GoodsNomenclatureOrigin",
                to="commodities.GoodsNomenclature",
            ),
        ),
        migrations.AddField(
            model_name="goodsnomenclature",
            name="successors",
            field=models.ManyToManyField(
                related_name="_goodsnomenclature_successors_+",
                through="commodities.GoodsNomenclatureSuccessor",
                to="commodities.GoodsNomenclature",
            ),
        ),
    ]
