# Generated by Django 3.0.10 on 2020-11-09 16:32
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0001_initial"),
        ("commodities", "0010_split_origin_successor_into_separate_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclatureindent",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclatureindent",
            name="exclude_overlapping_goods_indents",
        ),
        migrations.AddField(
            model_name="goodsnomenclatureindentnode",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="workbaskets.WorkBasket",
            ),
            preserve_default=False,
        ),
    ]
