# Generated by Django 3.0.10 on 2020-12-01 16:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0010_split_origin_successor_into_separate_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclature",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclature",
            name="exclude_overlapping_goods",
        ),
    ]
