# Generated by Django 3.1.13 on 2021-12-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("footnotes", "0006_allow_blank_descriptions"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("measures", "0010_add_requires_to_action_and_accepts_to_condition_code"),
        ("commodities", "0010_delete_goodsnomenclatureindentnode"),
        ("geo_areas", "0005_rename_described_area"),
        ("workbaskets", "0005_workbasket_rule_check_task_id"),
        ("importer", "0003_auto_20210302_1349"),
        ("taric", "0002_auto_20210219_1043"),
        ("exporter", "0004_upload_created_date"),
    ]

    operations = []
