# Generated by Django 3.1.13 on 2021-12-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0011_delete_goodsnomenclatureindentnode'),
    ]

    operations = [
    ]
