# Generated by Django 3.0.10 on 2020-12-07 22:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0011_auto_20201201_1611"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclaturedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="goodsnomenclatureindent",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclaturedescription",
            name="exclude_overlapping_goods_descriptions",
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclatureindent",
            name="exclude_overlapping_goods_indents",
        ),
    ]
