# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commodities",
            "0011_remove_indent_constraint_and_add_transaction_fk_to_nodes",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnoteassociationgoodsnomenclature",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
