# Generated by Django 3.1 on 2020-12-26 16:44
import django.db.models.deletion
from django.db import migrations
from django.db import models

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201226_1001"),
        ("commodities", "0011_auto_20201201_1611"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclaturedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="goodsnomenclatureindent",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclaturedescription",
            name="exclude_overlapping_goods_descriptions",
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclatureindent",
            name="exclude_overlapping_goods_indents",
        ),
        migrations.AddField(
            model_name="goodsnomenclatureindentnode",
            name="creating_transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_nomenclature_indent_nodes",
                to="common.transaction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
    ]
