# Generated by Django 3.1 on 2020-12-26 10:01
from django.db import migrations
from django.db import models

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0012_auto_20201207_2256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="sid",
            field=common.models.fields.NumericSID(),
        ),
    ]
