# Generated by Django 3.1 on 2020-12-28 09:52
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0012_auto_20201226_1644"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnoteassociationgoodsnomenclature",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(),
        ),
    ]
