# Generated by Django 3.0.11 on 2020-11-18 18:56
import django.core.validators
from django.db import migrations
from django.db import models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0012_auto_20201117_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnoteassociationgoodsnomenclature",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="sid",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="indent",
            field=models.PositiveIntegerField(
                db_index=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
    ]
