# Generated by Django 4.2.10 on 2024-02-23 11:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0012_TOPS_745_description_date_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="origins",
            field=models.ManyToManyField(
                through="commodities.GoodsNomenclatureOrigin",
                to="commodities.goodsnomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="successors",
            field=models.ManyToManyField(
                through="commodities.GoodsNomenclatureSuccessor",
                to="commodities.goodsnomenclature",
            ),
        ),
    ]
