# Generated by Django 3.1 on 2020-11-27 16:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0013_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
