# Generated by Django 3.1 on 2020-12-29 11:46
from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0013_auto_20201228_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnoteassociationgoodsnomenclature",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclature",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclaturedescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindent",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goodsnomenclatureindentnode",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
    ]
