# Generated by Django 3.1 on 2020-12-09 13:34
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0014_auto_20201127_1646"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclature",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclature",
            name="exclude_overlapping_goods",
        ),
    ]
