# Generated by Django 3.1 on 2020-12-11 22:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0015_auto_20201209_1334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsnomenclaturedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="goodsnomenclaturedescription",
            name="exclude_overlapping_goods_descriptions",
        ),
    ]
