# Containerised pytest:
#   $ docker-compose --file docker-compose.pytest.yml up --build pytest

version: "3"
services:

  # Container providing Postgresql instance to pytest.
  pytest-db:
    # With no persistent volume, it's possible to clear the database contents by
    # simply stopping this service: docker-compose stop pytest-db.
    image: "postgres:16"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_DB: tamato
    ports:
      # Map a port from the host to allow inspection via DB clients, e.g.:
      # $ psql --host=127.0.0.1 --port=5430 --username=postgres --dbname=tamato
      - "127.0.0.1:5430:5432"

  # Runs all tamato unit tests.
  pytest:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    image: pytest
    depends_on:
      - pytest-db
    environment:
      DATABASE_URL: postgres://postgres@pytest-db/tamato
      DJANGO_SETTINGS_MODULE: settings.test
      ENV: test
    command: sh -c "python manage.py migrate && pytest"
    stdin_open: true
    tty: true
