version: '3'
services:
  db:
    image: "postgres:12.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - tamato-data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tamato:
    build: .
    image: tamato
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"
      DJANGO_SETTINGS_MODULE: "settings.dev"
      ENABLE_DJANGO_DEBUG_TOOLBAR: "False"
      PYTHONUNBUFFERED: "1"
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
volumes:
  tamato-data-volume:
