version: '3'
services:
  db:
    image: "postgres:12.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  tamato:
    build: .
    image: tamato
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    env_file: .env
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"
      DJANGO_SETTINGS_MODULE: "settings.dev"
      ENABLE_DJANGO_DEBUG_TOOLBAR: "False"
      PYTHONUNBUFFERED: "1"
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py loaddata test-footnotes-fixtures test-user-fixtures
        python manage.py runserver 0.0.0.0:8000
