version: '3'
services:
  db:
    image: "postgres:12.8"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - tamato-data-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5431:5432"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    shm_size: 32g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache-redis:
    image: redis
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "127.0.0.1:6379:6379"

  celery-redis:
    image: redis
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "127.0.0.1:6378:6379"

  celery:
    build:
      context: .
      args:
        - "ENV=${ENV:-prod}"
    volumes:
      - ./:/app/
    command: ["celery", "-A" , "common.celery" ,"worker", "-O", "fair", "-l", "info"]
    env_file: 
      - .env
      - settings/envs/docker.env
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - celery-redis

  s3:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - tamato-s3-volume:/data
    env_file: .env
    entrypoint: sh
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    # TODO improve set up of buckets currently only hmrc-packaging set up automatically 
    command: ['-c', 'mkdir -p /data/hmrc-packaging && minio server --quiet /data --console-address ":9001"']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  tamato:
    build: 
      context: .
      args:
        - "ENV=${ENV:-prod}"
    image: tamato
    volumes:
      - "${DOCKER_WEB_VOLUME:-./:/app/}"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - s3
      - cache-redis
      - celery-redis
    env_file:
      - .env
      - settings/envs/docker.env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stdin_open: true
    tty: true     

volumes:
  tamato-data-volume: {}
  tamato-s3-volume: {}
