# Generated by Django 3.1.12 on 2021-06-28 17:09

from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testmodeldescription1",
            options={},
        ),
        migrations.AlterField(
            model_name="testmodeldescription1",
            name="validity_start",
            field=models.DateField(blank=False, db_index=True, null=False),
        ),
        migrations.AlterField(
            model_name="testmodeldescription1",
            name="description",
            field=common.fields.ShortDescription(),
        ),
    ]
