# Generated by Django 3.1.12 on 2021-07-14 15:22

from django.db import migrations

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_allow_blank_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel1",
            name="sid",
            field=common.fields.NumericSID(),
        ),
    ]
