# Generated by Django 3.0.8 on 2020-07-02 13:20
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedmodel",
            name="workbasket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_models",
                to="workbaskets.WorkBasket",
            ),
        ),
    ]
