# Generated by Django 3.2.6 on 2021-08-26 16:21

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    """
    Transaction partition field 1 of 3.

    1/3 Create Partition field, with partition defaulting to (1, SEED), as at the time of writing most of
    Transactions are from the seed file.

    2/3 Data migration to set Transaction partitions to (2, REVISION) and (3, DRAFT). REVISION:  Before this
    migration was written REVISION transactions are contained in workbaskets after the first workbasket with approved
    workbasket status. After this migration was written data schemas allow more control over SEED / REVISION
    transactions. DRAFT:   Draft Transactions are inferred by checking for transactions not in the first workbasket
    that lack an approved workbasket status..

    3/3
    Set the default value to (3, DRAFT)
    """

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("partition", "order")},
        ),
        migrations.AddField(
            model_name="transaction",
            name="partition",
            # Default is SEED here but later set to DRAFT - most data is seed
            # and this saves a lot of time updating in the database.
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Seed"), (2, "Revision"), (3, "Draft")],
                db_index=True,
                default=1,
                protected=True,
            ),
        ),
    ]
