# Generated by Django 3.0.8 on 2020-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20200702_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedmodel",
            name="update_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Update"), (2, "Delete"), (3, "Insert")], default=3
            ),
            preserve_default=False,
        ),
    ]
