# Generated by Django 3.2.6 on 2021-08-26 17:29

from django.db import migrations


def non_seed_transactions(apps):
    """:return: Queryset of non seed transactions."""
    Transaction = apps.get_model("common", "Transaction")
    Workbasket = apps.get_model("workbaskets", "Workbasket")

    return Transaction.objects.select_related("workbasket").exclude(
        workbasket=Workbasket.objects.first(),
    )


def infer_revision_transaction_partitions(apps, schemaeditor):
    """Infer the partition of Transactions to REVISION if they are not in the
    first workbasket and their workbasket status is approved."""
    from common.models.transactions import TransactionPartition
    from workbaskets.validators import WorkflowStatus

    apps.get_model("common", "Transaction")
    apps.get_model("workbaskets", "Workbasket")

    non_seed_transactions(apps).filter(
        workbasket__status__in=WorkflowStatus.approved_statuses(),
    ).update(partition=TransactionPartition.REVISION.value)


def infer_draft_transaction_partitions(apps, schemaeditor):
    """Infer the partition of Transactions to DRAFT if they are in an unapproved
    workbasket that isn't the first (seed) Workbasket."""
    from common.models.transactions import TransactionPartition
    from workbaskets.validators import WorkflowStatus

    non_seed_transactions(apps).exclude(
        workbasket__status__in=WorkflowStatus.approved_statuses(),
    ).update(partition=TransactionPartition.DRAFT.value)


class Migration(migrations.Migration):
    """
    Transaction partition field 2 of 3.

    1/3 Create Partition field, with partition defaulting to (1, SEED), as at the time of writing most of
    Transactions are from the seed file.

    2/3 Data migration to set Transaction partitions to (2, REVISION) and (3, DRAFT). REVISION:  Before this
    migration was written REVISION transactions are contained in workbaskets after the first workbasket with approved
    workbasket status. After this migration was written data schemas allow more control over SEED / REVISION
    transactions. DRAFT:   Draft Transactions are inferred by checking for transactions not in the first workbasket
    that lack an approved workbasket status..

    3/3
    Set the default value to (3, DRAFT)
    """

    dependencies = [
        ("common", "0002_transaction_partition_1_of_3"),
    ]

    operations = [
        migrations.RunPython(
            infer_revision_transaction_partitions,
            lambda apps, schema: None,
        ),
        migrations.RunPython(
            infer_draft_transaction_partitions,
            lambda apps, schema: None,
        ),
    ]
