# Generated by Django 3.0.4 on 2020-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_trackedmodel_update_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedmodel",
            name="update_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Update"), (2, "Delete"), (3, "Create")]
            ),
        ),
    ]
