# Generated by Django 3.1 on 2020-12-26 10:01
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0002_delete_transaction"),
        ("common", "0004_refactor_update_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_transaction_id",
                    models.IntegerField(editable=False, null=True),
                ),
                ("order", models.IntegerField()),
                (
                    "workbasket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="workbaskets.workbasket",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="trackedmodel",
            name="workbasket",
        ),
        migrations.CreateModel(
            name="TransactionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.IntegerField()),
                ("order_in_group", models.IntegerField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trackedmodel",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_models",
                to="common.transaction",
            ),
            preserve_default=False,
        ),
    ]
