# Generated by Django 3.1.14 on 2022-02-21 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_transaction_index"),
        ("measures", "0010_add_requires_to_action_and_accepts_to_condition_code"),
    ]

    operations = []
