# Generated by Django 3.0.11 on 2020-11-18 18:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201029_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedmodel",
            name="update_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Update"), (2, "Delete"), (3, "Create")], db_index=True
            ),
        ),
    ]
