# Generated by Django 3.1 on 2020-12-28 09:52
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201226_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="composite_key",
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="versiongroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="versiongroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trackedmodel",
            name="update_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Update"), (2, "Delete"), (3, "Create")], db_index=True
            ),
        ),
    ]
