# Generated by Django 3.1.14 on 2022-02-21 14:57

from django.db import migrations


def current_versions_without_tracked_models(apps):
    from common.models.transactions import TransactionPartition
    from workbaskets.validators import WorkflowStatus

    """:return: Queryset of tracked models with no current version, but are published, and on the correct partition."""

    TrackedModel = apps.get_model("common", "TrackedModel")

    return (
        TrackedModel.objects.select_related("version_group")
        .filter(
            version_group__current_version_id__isnull=True,
        )
        .select_related("transaction")
        .filter(
            transaction__partition=TransactionPartition.REVISION,
            transaction__workbasket__status=WorkflowStatus.PUBLISHED,
        )
        .order_by("transaction__order")
    )


def fix_current_versions(apps, schemaeditor):
    """Update affected models and run through in transaction order, to correctly
    update the missing correct current version."""

    results = current_versions_without_tracked_models(apps)

    for result in results:
        version_group = result.version_group
        version_group.current_version_id = result.id
        version_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_auto_20221114_1000"),
    ]

    operations = [
        migrations.RunPython(
            fix_current_versions,
            lambda apps, schema: None,
        ),
    ]
