# Generated by Django 3.1 on 2020-12-12 21:19
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_auto_20201118_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="versiongroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="versiongroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
