# Generated by Django 3.1.14 on 2022-05-10 14:09

from django.db import migrations

"""
Data migration to move transactions in ARCHIVED workbaskets to the ARCHIVED transaction partition.
"""


def get_archived_workbasket_transactions(apps):
    """Return Transactions belonging to archived Workbaskets."""
    from workbaskets.validators import WorkflowStatus

    Transaction = apps.get_model("common", "Transaction")

    return Transaction.objects.select_related("workbasket").filter(
        workbasket__status=WorkflowStatus.ARCHIVED,
    )


def move_archived_workbasket_transaction_to_archived_partition(apps, schemaeditor):
    """Move Transactions belonging to archived Workbaskets to the ARCHIVED
    Partition."""
    from common.models.transactions import TransactionPartition

    get_archived_workbasket_transactions(apps).update(
        partition=TransactionPartition.ARCHIVED,
    )


def move_archived_workbasket_transaction_to_draft_partition(apps, schemaeditor):
    """Move Transactions belonging to archived Workbaskets to the ARCHIVED
    Partition."""
    from common.models.transactions import TransactionPartition

    get_archived_workbasket_transactions(apps).update(
        partition=TransactionPartition.DRAFT,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_transaction_add_archive_partition_schema"),
    ]

    operations = [
        migrations.RunPython(
            move_archived_workbasket_transaction_to_draft_partition,
            reverse_code=move_archived_workbasket_transaction_to_draft_partition,
        ),
    ]
