# Generated by Django 3.1 on 2020-12-29 14:34
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_auto_20201228_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versiongroup",
            name="current_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="is_current",
                to="common.trackedmodel",
            ),
        ),
    ]
