# Generated by Django 3.2.23 on 2023-12-11 16:42

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_auto_20221114_1040_fix_missing_current_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trackedmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
