# Generated by Django 3.2.23 on 2024-01-24 15:41

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0008_datarow_dataupload"),
        ("common", "0007_auto_20221114_1040_fix_missing_current_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_workbasket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workbaskets.workbasket",
            ),
        ),
    ]
