# Generated by Django 4.2.14 on 2024-07-31 16:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_trackedmodel_polymorphic_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sso_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
