# Generated by Django 4.2.15 on 2024-10-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_user_sso_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="versiongroup",
            old_name="current_version",
            new_name="latest_approved_version",
        ),
    ]
