# Generated by Django 4.2.18 on 2025-02-11 14:47

from django.db import migrations

import common.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_user_sso_uuid"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.models.user.TamatoUserManager()),
            ],
        ),
    ]
