# Generated by Django 4.2.18 on 2025-02-11 15:48

from django.db import migrations

import common.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_versiongroup_common_vers_current_04c358_idx"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.models.user.TamatoUserManager()),
            ],
        ),
    ]
