# Generated by Django 3.0.6 on 2020-06-03 16:11

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import footnotes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootnoteType',
            fields=[
                ('trackedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TrackedModel')),
                ('valid_between', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('footnote_type_id', models.CharField(max_length=3, unique=True, validators=[footnotes.validators.valid_footnote_type_id])),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('common.trackedmodel', models.Model),
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('trackedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TrackedModel')),
                ('valid_between', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('footnote_id', models.CharField(max_length=5, unique=True, validators=[footnotes.validators.valid_footnote_id])),
                ('description', models.CharField(max_length=500)),
                ('footnote_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footnotes.FootnoteType')),
            ],
            options={
                'ordering': ['footnote_type__footnote_type_id', 'footnote_id'],
            },
            bases=('common.trackedmodel', models.Model),
        ),
    ]
