# Generated by Django 3.1 on 2021-02-01 16:39
from django.db import migrations

from common.migration_operations import ConvertTaricDateRange


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0001_initial"),
    ]

    operations = [
        ConvertTaricDateRange("footnote", "valid_between"),
        ConvertTaricDateRange("footnotedescription", "valid_between"),
        ConvertTaricDateRange("footnotetype", "valid_between"),
    ]
