# Generated by Django 3.0.4 on 2020-04-22 15:41
from datetime import datetime
from datetime import timezone

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations
from django.db import models
from psycopg2.extras import DateTimeTZRange

BREXIT_DATE = datetime(2021, 1, 1, tzinfo=timezone.utc)
MAX_DATE = datetime.max.replace(tzinfo=timezone.utc)


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootnoteDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national", models.BooleanField(default=False)),
                ("description", models.TextField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="FootnoteType",
            fields=[
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("live", models.BooleanField(default=False)),
                ("national", models.BooleanField(default=False)),
                (
                    "id",
                    models.CharField(
                        blank=True, max_length=2, primary_key=True, serialize=False
                    ),
                ),
                ("application_code", models.IntegerField()),
                ("description", models.TextField()),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="footnote", name="description",),
        migrations.AddField(
            model_name="footnote",
            name="live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="footnote",
            name="national",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="footnote",
            name="valid_between",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                default=DateTimeTZRange(BREXIT_DATE, MAX_DATE)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="footnote",
            name="id",
            field=models.CharField(
                blank=True, max_length=5, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="FootnoteDescriptionPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("live", models.BooleanField(default=False)),
                ("national", models.BooleanField(default=False)),
                (
                    "footnote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="footnotes.Footnote",
                    ),
                ),
                (
                    "footnote_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="footnotes.FootnoteDescription",
                    ),
                ),
                (
                    "footnote_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="footnotes.FootnoteType",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="footnotedescription",
            name="footnote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="footnotes.Footnote"
            ),
        ),
        migrations.AddField(
            model_name="footnotedescription",
            name="footnote_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="footnotes.FootnoteType"
            ),
        ),
        migrations.AddField(
            model_name="footnote",
            name="footnote_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="footnotes.FootnoteType",
            ),
            preserve_default=False,
        ),
    ]
