# Generated by Django 3.0.4 on 2020-07-24 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0002_refactor_footnotes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnotedescription", options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="footnote", name="exclude_overlapping_footnotes_FO2",
        ),
        migrations.RemoveConstraint(
            model_name="footnotedescription",
            name="exclude_overlapping_footnote_descriptions",
        ),
        migrations.AddField(
            model_name="footnote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
