# Generated by Django 3.0.4 on 2020-05-18 16:56
from django.db import migrations
from django.db import models

import footnotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0002_footnotes_and_footnote_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnote",
            options={"ordering": ["footnote_type__footnote_type_id", "footnote_id"]},
        ),
        migrations.AlterField(
            model_name="footnote",
            name="footnote_id",
            field=models.CharField(
                max_length=5, validators=[footnotes.validators.valid_footnote_id]
            ),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="footnote_type_id",
            field=models.CharField(
                max_length=3,
                unique=True,
                validators=[footnotes.validators.valid_footnote_type_id],
            ),
        ),
        migrations.AddConstraint(
            model_name="footnote",
            constraint=models.UniqueConstraint(
                fields=("footnote_id", "footnote_type"), name="FO2"
            ),
        ),
    ]
