# Generated by Django 3.0.4 on 2020-05-26 12:08

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import footnotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0002_footnotes_and_footnote_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootnoteDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("live", models.BooleanField(default=False)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FootnoteTypeDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name="footnote",
            options={"ordering": ["footnote_type__footnote_type_id", "footnote_id"]},
        ),
        migrations.RemoveField(model_name="footnote", name="description",),
        migrations.RemoveField(model_name="footnotetype", name="description",),
        migrations.AddField(
            model_name="footnotetype",
            name="application_code",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Cn Nomenclature"),
                    (2, "Taric Nomenclature"),
                    (3, "Export Refund Nomenclature"),
                    (4, "Wine Reference Nomenclature"),
                    (5, "Additional Codes"),
                    (6, "Cn Measures"),
                    (7, "Other Measures"),
                    (8, "Meursing Heading"),
                    (9, "Dynamic Footnote"),
                ],
                default=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="footnote",
            name="footnote_id",
            field=models.CharField(
                max_length=5, validators=[footnotes.validators.FootnoteIDValidator]
            ),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="footnote_type_id",
            field=models.CharField(
                max_length=3,
                unique=True,
                validators=[footnotes.validators.FootnoteTypeIDValidator],
            ),
        ),
        migrations.AddConstraint(
            model_name="footnote",
            constraint=models.UniqueConstraint(
                fields=("footnote_id", "footnote_type"), name="FO2"
            ),
        ),
        migrations.AddField(
            model_name="footnotetypedescription",
            name="footnote_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="footnotes.FootnoteType"
            ),
        ),
        migrations.AddField(
            model_name="footnotedescription",
            name="footnote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="footnotes.Footnote"
            ),
        ),
        migrations.AddConstraint(
            model_name="footnotedescription",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (django.db.models.functions.text.Lower("valid_between"), "="),
                    ("footnote", "="),
                ],
                name="FO4",
            ),
        ),
    ]
