# Generated by Django 3.1 on 2021-04-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0003_auto_20210219_0955"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footnotedescription",
            old_name="description_period_sid",
            new_name="sid",
        ),
    ]
