# Generated by Django 3.0.10 on 2020-09-23 23:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0004_use_common_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnotetype",
            name="application_code",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "CN nomenclature"),
                    (2, "TARIC nomenclature"),
                    (3, "Export refund nomenclature"),
                    (4, "Wine reference nomenclature"),
                    (5, "Additional codes"),
                    (6, "CN measures"),
                    (7, "Other measures"),
                    (8, "Meursing Heading"),
                    (9, "Dynamic footnote"),
                ]
            ),
        ),
    ]
