# Generated by Django 3.0.10 on 2020-10-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0005_add_measures_data_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnotetype",
            name="footnote_type_id",
            field=models.CharField(
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator("^[A-Z0-9]{2}[A-Z0-9 ]?$")
                ],
            ),
        ),
    ]
