# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0006_national_schema_footnote_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnotedescription",
            name="description_period_sid",
            field=common.models.SignedIntSID(),
        ),
    ]
