# Generated by Django 3.0.10 on 2020-11-27 17:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0007_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnotetype",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="footnotetype",
            name="exclude_overlapping_footnote_types",
        ),
    ]
