# Generated by Django 3.0.10 on 2020-10-30 17:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0007_auto_20201027_1022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footnote",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="footnote",
            name="updated_at",
        ),
    ]
