# Generated by Django 3.1 on 2020-12-26 16:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0008_auto_20201030_1737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnotetype",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="footnotetype",
            name="exclude_overlapping_footnote_types",
        ),
    ]
