# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0008_auto_20201030_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnotedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
