# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0009_auto_20201226_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnotedescription",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
