# Generated by Django 3.1 on 2020-12-29 11:47
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0009_auto_20201226_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="footnote_id",
            field=models.CharField(
                db_index=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator("^([0-9]{3}|[0-9]{5})$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="footnote",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="footnotedescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="footnote_type_id",
            field=models.CharField(
                db_index=True,
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator("^[A-Z0-9]{2}[A-Z0-9 ]?$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="footnotetype",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
    ]
