# Generated by Django 3.0.9 on 2020-08-13 11:13
import django.core.validators
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=common.fields.ShortDescription(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="information_text",
            field=common.fields.ShortDescription(
                blank=True,
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^|]*$", "Must not contain '|'"
                    )
                ],
            ),
        ),
    ]
