# Generated by Django 3.1.2 on 2020-10-15 13:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0002_use_common_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="replacement_indicator",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not replaced"),
                    (1, "Replaced"),
                    (2, "Partially replaced"),
                ],
                default=0,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="role_type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Base"),
                    (2, "Provisional anti-dumping"),
                    (3, "Definitive anti-dumping"),
                    (4, "Modification"),
                    (5, "Prorogation"),
                    (6, "Complete abrogation"),
                    (7, "Explicit abrogation"),
                    (8, "Full temporary stop"),
                ],
                default=1,
                editable=False,
            ),
        ),
    ]
