# Generated by Django 3.0.10 on 2020-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0003_refactor_enums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="community_code",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Economic"),
                    (2, "Atomic"),
                    (3, "Coal"),
                    (4, "Economic/Coal"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
