# Generated by Django 3.1.6 on 2021-04-30 09:37

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0004_auto_20210211_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="regulation_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="The regulation number",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([CRDAIJ]\\d{2}\\d{4}[0-9A-Z]|[CPUSXNMQA]\\d{2}\\d{4}[0-9A-Z]|[ZV]\\d{4}[A-Z]{3}|IYY\\d{5})$",
                    ),
                ],
            ),
        ),
    ]
