# Generated by Django 3.0.10 on 2020-10-04 22:02
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0004_make_community_code_default_for_regulations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="regulation_id",
            field=models.CharField(
                editable=False,
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "(?x)\n    ((?P<prefix>C|R|D|A|I|J|P|U|S|X|N|M|Q|0)\n    (?P<year>\\d{2})\n    (?P<number>\\d{4})\n    (?P<suffix>[0-9A-Z]))|\n    ((?P<national_prefix>Z|V)\n    (?P<national_year>\\d{4})\n    (?P<national_suffix>[A-Z]{3}))|\n    ((?P<dummy_prefix>IYY)\n    (?P<dummy_suffix>\\d{5}))\n"
                    )
                ],
            ),
        ),
    ]
