# Generated by Django 3.1.12 on 2021-07-15 08:43

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0005_auto_20210430_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="An unapproved status means none of the measures that link to this regulation will be active at the border.",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="published_at",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The date that the source for this regulation was published. For a Statutory Instrument (S.I.) or other peice of UK legislation, this should be the “made date” as found in the introductory note of the legislative text.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation_group",
            field=models.ForeignKey(
                blank=True,
                help_text="If the wrong regulation group is selected, a trader's declaration may be rejected.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="regulations.group",
            ),
        ),
    ]
