# Generated by Django 3.0.10 on 2020-10-26 11:07
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0005_national_schema_regulation_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="regulation_id",
            field=models.CharField(
                editable=False,
                help_text="The regulation number",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "(?x)\n    ((?P<prefix>C|R|D|A|I|J|P|U|S|X|N|M|Q|0)\n    (?P<year>\\d{2})\n    (?P<number>\\d{4})\n    (?P<suffix>[0-9A-Z]))|\n    ((?P<national_prefix>Z|V)\n    (?P<national_year>\\d{4})\n    (?P<national_suffix>[A-Z]{3}))|\n    ((?P<dummy_prefix>IYY)\n    (?P<dummy_suffix>\\d{5}))\n"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="replacement",
            name="geographical_area_id",
            field=models.CharField(
                max_length=4,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^[A-Z0-9]{2}$|^[A-Z0-9]{4}$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="replacement",
            name="measure_type_id",
            field=models.CharField(
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{3}|[0-9]{6}|[A-Z]{3}$"
                    )
                ],
            ),
        ),
    ]
