# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0006_refactor_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
