# Generated by Django 3.1.12 on 2021-07-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_auto_20210715_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='published_at',
            field=models.DateField(blank=True, help_text='The date that the source for this regulation was published. For a Statutory Instrument (S.I.) or other peice of UK legislation, this should be the “made date” as found in the introductory note of the legislative text.', null=True),
        ),
    ]
