# Generated by Django 3.1 on 2020-12-29 11:47
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0006_refactor_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="effective_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=3,
                validators=[django.core.validators.RegexValidator("[A-Z][A-Z][A-Z]")],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="regulation_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="The regulation number",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "(?x)\n    ((?P<prefix>C|R|D|A|I|J|P|U|S|X|N|M|Q|0)\n    (?P<year>\\d{2})\n    (?P<number>\\d{4})\n    (?P<suffix>[0-9A-Z]))|\n    ((?P<national_prefix>Z|V)\n    (?P<national_year>\\d{4})\n    (?P<national_suffix>[A-Z]{3}))|\n    ((?P<dummy_prefix>IYY)\n    (?P<dummy_suffix>\\d{5}))\n"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="role_type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Base"),
                    (2, "Provisional anti-dumping"),
                    (3, "Definitive anti-dumping"),
                    (4, "Modification"),
                    (5, "Prorogation"),
                    (6, "Complete abrogation"),
                    (7, "Explicit abrogation"),
                    (8, "Full temporary stop"),
                ],
                db_index=True,
                default=1,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="replacement",
            name="chapter_heading",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="replacement",
            name="geographical_area_id",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^[A-Z0-9]{2}$|^[A-Z0-9]{4}$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="replacement",
            name="measure_type_id",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{3}|[0-9]{6}|[A-Z]{3}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="suspension",
            name="effective_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
