# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0006_refactor_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
