# Generated by Django 3.1.12 on 2021-07-16 17:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0008_auto_20210715_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
