# Generated by Django 4.2.10 on 2024-02-23 11:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0009_auto_20210716_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="amends",
            field=models.ManyToManyField(
                related_name="+",
                through="regulations.Amendment",
                to="regulations.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="extends",
            field=models.ManyToManyField(
                related_name="+",
                through="regulations.Extension",
                to="regulations.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="replaces",
            field=models.ManyToManyField(
                related_name="+",
                through="regulations.Replacement",
                to="regulations.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="suspends",
            field=models.ManyToManyField(
                related_name="+",
                through="regulations.Suspension",
                to="regulations.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="regulation",
            name="terminates",
            field=models.ManyToManyField(
                related_name="+",
                through="regulations.Termination",
                to="regulations.regulation",
            ),
        ),
    ]
