# Generated by Django 3.2.23 on 2024-01-29 14:52

import django.db.models.deletion
import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Short name for this workbasket",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.FloatField()),
                ("published_date", models.DateField()),
                ("entry_into_force_date", models.DateField()),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("EDITING", "Editing"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="EDITING",
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_document_versions",
                        to="reference_documents.referencedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_rates",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota_order_number", models.CharField(db_index=True, max_length=6)),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("quota_duty_rate", models.CharField(max_length=255)),
                ("volume", models.FloatField()),
                ("quota_period_open", models.DateField()),
                ("quota_period_close", models.DateField()),
                ("measurement", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quotas",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
    ]
