# Generated by Django 3.2.23 on 2024-02-08 09:34

import django.db.models.deletion
import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlignmentReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Short name for this workbasket",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("area_id", models.CharField(db_index=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceDocumentVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.FloatField()),
                ("published_date", models.DateField(blank=True, null=True)),
                ("entry_into_force_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("EDITING", "Editing"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="EDITING",
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_document_versions",
                        to="reference_documents.referencedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                ("valid_start_day", models.IntegerField(blank=True, null=True)),
                ("valid_start_month", models.IntegerField(blank=True, null=True)),
                ("valid_end_day", models.IntegerField(blank=True, null=True)),
                ("valid_end_month", models.IntegerField(blank=True, null=True)),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_rates",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota_order_number", models.CharField(db_index=True, max_length=6)),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("quota_duty_rate", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=255)),
                ("valid_start_day", models.IntegerField(blank=True, null=True)),
                ("valid_start_month", models.IntegerField(blank=True, null=True)),
                ("valid_end_day", models.IntegerField(blank=True, null=True)),
                ("valid_end_month", models.IntegerField(blank=True, null=True)),
                ("measurement", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quotas",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlignmentReportCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("check_name", models.CharField(max_length=255)),
                ("successful", models.BooleanField()),
                ("message", models.TextField(null=True)),
                (
                    "alignment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_report_checks",
                        to="reference_documents.alignmentreport",
                    ),
                ),
                (
                    "preferential_quota",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_report_checks",
                        to="reference_documents.preferentialquota",
                    ),
                ),
                (
                    "preferential_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_report_checks",
                        to="reference_documents.preferentialrate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alignmentreport",
            name="reference_document_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alignment_reports",
                to="reference_documents.referencedocumentversion",
            ),
        ),
    ]
