# Generated by Django 4.2.11 on 2024-05-08 08:40

import django.db.models.deletion
import django_fsm
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Short name for this reference document",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("area_id", models.CharField(db_index=True, max_length=4, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferenceDocumentVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.FloatField()),
                ("published_date", models.DateField(blank=True, null=True)),
                ("entry_into_force_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("EDITING", "Editing"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="EDITING",
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_document_versions",
                        to="reference_documents.referencedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_rates",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuotaOrderNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota_order_number", models.CharField(db_index=True, max_length=6)),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "main_order_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_order_number",
                        to="reference_documents.preferentialquotaordernumber",
                    ),
                ),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_order_numbers",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("quota_duty_rate", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=255)),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                    ),
                ),
                ("measurement", models.CharField(max_length=255)),
                (
                    "preferential_quota_order_number",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quotas",
                        to="reference_documents.preferentialquotaordernumber",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="referencedocumentversion",
            constraint=models.UniqueConstraint(
                fields=("version", "reference_document"),
                name="unique_versions",
            ),
        ),
    ]
