# Generated by Django 3.2.24 on 2024-02-28 15:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedocument",
            name="area_id",
            field=models.CharField(db_index=True, max_length=4, unique=True),
        ),
    ]
