# Generated by Django 4.2.11 on 2024-04-04 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferentialquota",
            name="order",
        ),
        migrations.RemoveField(
            model_name="preferentialrate",
            name="order",
        ),
    ]
