# Generated by Django 3.2.23 on 2024-02-15 10:56

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="successful",
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PASS", "Passing"),
                    ("FAIL", "Failed"),
                    ("WARNING", "Warning"),
                ],
                db_index=True,
                default="FAIL",
                editable=False,
                max_length=50,
            ),
        ),
    ]
