# Generated by Django 4.2.11 on 2024-05-13 07:54

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_reports",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlignmentReportCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("check_name", models.CharField(max_length=255)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("PASS", "Passing"),
                            ("FAIL", "Failed"),
                            ("WARNING", "Warning"),
                        ],
                        db_index=True,
                        default="FAIL",
                        editable=False,
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(null=True)),
                (
                    "alignment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_report_checks",
                        to="reference_documents.alignmentreport",
                    ),
                ),
                (
                    "preferential_quota",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_checks",
                        to="reference_documents.preferentialquota",
                    ),
                ),
                (
                    "preferential_quota_order_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_order_number_checks",
                        to="reference_documents.preferentialquotaordernumber",
                    ),
                ),
                (
                    "preferential_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_rate_checks",
                        to="reference_documents.preferentialrate",
                    ),
                ),
            ],
        ),
    ]
