# Generated by Django 3.2.23 on 2024-01-30 16:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencedocument",
            name="area_id",
            field=models.CharField(db_index=True, default="ZZ", max_length=4),
            preserve_default=False,
        ),
    ]
