# Generated by Django 4.2.11 on 2024-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0002_remove_preferentialquota_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedocument",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Short name for this reference document",
                max_length=255,
                unique=True,
            ),
        ),
    ]
