# Generated by Django 4.2.11 on 2024-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0002_alignmentreport_alignmentreportcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
