# Generated by Django 3.2.24 on 2024-03-07 08:48

import django.db.models.deletion
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0002_alter_referencedocument_area_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferentialQuotaOrderNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota_order_number", models.CharField(db_index=True, max_length=6)),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="preferentialquota",
            name="coefficient",
        ),
        migrations.RemoveField(
            model_name="preferentialquota",
            name="main_quota",
        ),
        migrations.RemoveField(
            model_name="preferentialquota",
            name="quota_order_number",
        ),
        migrations.RemoveField(
            model_name="preferentialquota",
            name="reference_document_version",
        ),
        migrations.RemoveField(
            model_name="preferentialrate",
            name="reference_document_version",
        ),
        migrations.AddConstraint(
            model_name="referencedocumentversion",
            constraint=models.UniqueConstraint(
                fields=("version", "reference_document"),
                name="unique_versions",
            ),
        ),
        migrations.AddField(
            model_name="preferentialquotaordernumber",
            name="main_order_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_order_number",
                to="reference_documents.preferentialquotaordernumber",
            ),
        ),
        migrations.AddField(
            model_name="preferentialquotaordernumber",
            name="reference_document_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_order_numbers",
                to="reference_documents.referencedocumentversion",
            ),
        ),
        migrations.AddField(
            model_name="preferentialquota",
            name="preferential_quota_order_number",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_order_number",
                to="reference_documents.preferentialquotaordernumber",
            ),
        ),
    ]
