# Generated by Django 3.2.23 on 2024-02-19 09:51

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0002_auto_20240215_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alignmentreportcheck",
            name="preferential_quota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_checks",
                to="reference_documents.preferentialquota",
            ),
        ),
        migrations.AlterField(
            model_name="alignmentreportcheck",
            name="preferential_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_rate_checks",
                to="reference_documents.preferentialrate",
            ),
        ),
    ]
