# Generated by Django 3.2.23 on 2024-02-01 09:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0002_referencedocument_area_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferentialrate",
            name="valid_end_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialrate",
            name="valid_end_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialrate",
            name="valid_start_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialrate",
            name="valid_start_month",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
