# Generated by Django 3.2.23 on 2024-02-02 09:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0003_auto_20240201_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedocumentversion",
            name="entry_into_force_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="referencedocumentversion",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
