# Generated by Django 4.2.11 on 2024-05-23 10:35

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0003_alignmentreport_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferentialQuotaTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("quota_duty_rate", models.CharField(max_length=255)),
                ("initial_volume", models.CharField(max_length=255)),
                ("yearly_volume_increment", models.CharField(max_length=255)),
                ("start_day", models.PositiveSmallIntegerField()),
                ("start_month", models.PositiveSmallIntegerField()),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_day", models.PositiveSmallIntegerField()),
                ("end_month", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("measurement", models.CharField(max_length=255)),
                (
                    "preferential_quota_order_number",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_templates",
                        to="reference_documents.preferentialquotaordernumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuotaSuspensionTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField()),
                ("start_month", models.PositiveSmallIntegerField()),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_day", models.PositiveSmallIntegerField()),
                ("end_month", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "preferential_quota_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_suspension_templates",
                        to="reference_documents.preferentialquotatemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreferentialQuotaSuspension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "preferential_quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferential_quota_suspensions",
                        to="reference_documents.preferentialquota",
                    ),
                ),
            ],
        ),
    ]
