# Generated by Django 3.2.24 on 2024-03-07 08:52

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0003_auto_20240307_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferentialrate",
            name="reference_document_version",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_rates",
                to="reference_documents.referencedocumentversion",
            ),
        ),
    ]
