# Generated by Django 4.2.11 on 2024-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0004_preferentialquotatemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferentialquotatemplate",
            name="yearly_volume_increment_text",
            field=models.CharField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preferentialquotatemplate",
            name="initial_volume",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="preferentialquotatemplate",
            name="yearly_volume_increment",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
