# Generated by Django 3.2.23 on 2024-02-02 14:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0004_auto_20240202_0936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferentialquota",
            name="quota_period_close",
        ),
        migrations.RemoveField(
            model_name="preferentialquota",
            name="quota_period_open",
        ),
        migrations.AddField(
            model_name="preferentialquota",
            name="valid_end_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialquota",
            name="valid_end_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialquota",
            name="valid_start_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preferentialquota",
            name="valid_start_month",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
