# Generated by Django 4.2.11 on 2024-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_documents",
            "0005_preferentialquotatemplate_yearly_volume_increment_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferentialquotatemplate",
            name="yearly_volume_increment_text",
            field=models.TextField(),
        ),
    ]
