# Generated by Django 3.2.24 on 2024-03-07 09:17

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reference_documents",
            "0005_alter_preferentialquota_preferential_quota_order_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferentialquota",
            name="preferential_quota_order_number",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quotas",
                to="reference_documents.preferentialquotaordernumber",
            ),
        ),
    ]
