# Generated by Django 3.2.23 on 2024-02-02 14:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_documents", "0005_auto_20240202_1431"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferentialquota",
            name="volume",
            field=models.CharField(max_length=255),
        ),
    ]
