# Generated by Django 3.2.24 on 2024-03-07 14:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reference_documents",
            "0006_alter_preferentialquota_preferential_quota_order_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="preferential_quota_order_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_order_number_checks",
                to="reference_documents.preferentialquotaordernumber",
            ),
        ),
    ]
