# Generated by Django 4.2.11 on 2024-06-13 07:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_documents",
            "0006_alter_preferentialquotatemplate_yearly_volume_increment_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentreport",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETE", "Complete"),
                    ("ERRORED", "Errored"),
                ],
                db_index=True,
                default="PENDING",
                editable=False,
                max_length=50,
            ),
        ),
    ]
