# Generated by Django 4.2.11 on 2024-06-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0007_alignmentreport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="preferential_quota_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_template_checks",
                to="reference_documents.preferentialquotatemplate",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="preferential_suspension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_suspension_checks",
                to="reference_documents.preferentialquotasuspension",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="preferential_suspension_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferential_quota_suspension_template_checks",
                to="reference_documents.preferentialquotasuspensiontemplate",
            ),
        ),
    ]
