# Generated by Django 4.2.11 on 2024-06-18 09:07

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_documents",
            "0008_alignmentreportcheck_preferential_quota_template_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RefOrderNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(db_index=True, max_length=6)),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "sub_quota_relation_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equivalent to main quota"),
                            ("NM", "Normal (restrictive to main quota)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "main_order_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_order_number",
                        to="reference_documents.refordernumber",
                    ),
                ),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_order_numbers",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefQuotaDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=255)),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                ("measurement", models.CharField(max_length=255)),
                (
                    "ref_order_number",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_quota_definitions",
                        to="reference_documents.refordernumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefQuotaDefinitionRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                ("initial_volume", models.IntegerField()),
                (
                    "yearly_volume_increment",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("yearly_volume_increment_text", models.TextField()),
                ("start_day", models.PositiveSmallIntegerField()),
                ("start_month", models.PositiveSmallIntegerField()),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_day", models.PositiveSmallIntegerField()),
                ("end_month", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("measurement", models.CharField(max_length=255)),
                (
                    "ref_order_number",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_quota_definition_ranges",
                        to="reference_documents.refordernumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefQuotaSuspension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "ref_quota_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_quota_suspensions",
                        to="reference_documents.refquotadefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefQuotaSuspensionRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_day", models.PositiveSmallIntegerField()),
                ("start_month", models.PositiveSmallIntegerField()),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_day", models.PositiveSmallIntegerField()),
                ("end_month", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "ref_quota_definition_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_quota_suspension_range",
                        to="reference_documents.refquotadefinitionrange",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_code", models.CharField(db_index=True, max_length=10)),
                ("duty_rate", models.CharField(max_length=255)),
                (
                    "valid_between",
                    common.fields.TaricDateRangeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "reference_document_version",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ref_rates",
                        to="reference_documents.referencedocumentversion",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="preferentialquotaordernumber",
            name="main_order_number",
        ),
        migrations.RemoveField(
            model_name="preferentialquotaordernumber",
            name="reference_document_version",
        ),
        migrations.RemoveField(
            model_name="preferentialquotasuspension",
            name="preferential_quota",
        ),
        migrations.RemoveField(
            model_name="preferentialquotasuspensiontemplate",
            name="preferential_quota_template",
        ),
        migrations.RemoveField(
            model_name="preferentialquotatemplate",
            name="preferential_quota_order_number",
        ),
        migrations.RemoveField(
            model_name="preferentialrate",
            name="reference_document_version",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_quota",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_quota_order_number",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_quota_template",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_rate",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_suspension",
        ),
        migrations.RemoveField(
            model_name="alignmentreportcheck",
            name="preferential_suspension_template",
        ),
        migrations.AlterField(
            model_name="alignmentreportcheck",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("PASS", "Passing"),
                    ("FAIL", "Failed"),
                    ("WARNING", "Warning"),
                    ("SKIPPED", "Skipped"),
                ],
                db_index=True,
                default="FAIL",
                editable=False,
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="PreferentialQuota",
        ),
        migrations.DeleteModel(
            name="PreferentialQuotaOrderNumber",
        ),
        migrations.DeleteModel(
            name="PreferentialQuotaSuspension",
        ),
        migrations.DeleteModel(
            name="PreferentialQuotaSuspensionTemplate",
        ),
        migrations.DeleteModel(
            name="PreferentialQuotaTemplate",
        ),
        migrations.DeleteModel(
            name="PreferentialRate",
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_order_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_order_number_checks",
                to="reference_documents.refordernumber",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_quota_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_quota_definition_checks",
                to="reference_documents.refquotadefinition",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_quota_definition_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_quota_definition_range_checks",
                to="reference_documents.refquotadefinitionrange",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_quota_suspension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_quota_suspension_checks",
                to="reference_documents.refquotasuspension",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_quota_suspension_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_quota_suspension_range_checks",
                to="reference_documents.refquotasuspensionrange",
            ),
        ),
        migrations.AddField(
            model_name="alignmentreportcheck",
            name="ref_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_rate_checks",
                to="reference_documents.refrate",
            ),
        ),
    ]
