# Generated by Django 4.2.11 on 2024-06-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0009_refordernumber_refquotadefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencedocument",
            name="regulations",
            field=models.TextField(
                blank=True, default=None, help_text="List of regulation ids", null=True
            ),
        ),
        migrations.AlterField(
            model_name="refquotasuspensionrange",
            name="ref_quota_definition_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ref_quota_suspension_ranges",
                to="reference_documents.refquotadefinitionrange",
            ),
        ),
    ]
