# Generated by Django 4.2.11 on 2024-06-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_documents", "0010_referencedocument_regulations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refordernumber",
            old_name="sub_quota_relation_type",
            new_name="relation_type",
        ),
    ]
