# Generated by Django 3.0.7 on 2020-07-01 08:39

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "sid",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9]{3}$")
                        ],
                    ),
                ),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="CertificateDescription",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "sid",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999999)]
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "sid",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9]{1}$")
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.AddConstraint(
            model_name="certificatetype",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_certificate_types",
            ),
        ),
        migrations.AddField(
            model_name="certificatedescription",
            name="described_certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descriptions",
                to="certificates.Certificate",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="certificates.CertificateType",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificatedescription",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_certificate_descriptions",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_certificates",
            ),
        ),
    ]
