# Generated by Django 3.0.10 on 2020-09-25 19:33

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_use_common_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="certificate",
            name="exclude_overlapping_certificates",
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("valid_between", "&&"),
                    ("sid", "="),
                    ("certificate_type", "="),
                ],
                name="exclude_overlapping_certificates",
            ),
        ),
    ]
