# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_certificate_exclusion_includes_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatedescription",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
    ]
