# Generated by Django 3.0.10 on 2020-12-01 15:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0004_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificatetype",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificatetype",
            name="exclude_overlapping_certificate_types",
        ),
    ]
