# Generated by Django 3.0.10 on 2020-12-01 15:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_auto_20201201_1524"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificate",
            name="exclude_overlapping_certificates",
        ),
    ]
