# Generated by Django 3.1 on 2020-12-29 11:47
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_auto_20201201_1524"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="certificatedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificate",
            name="exclude_overlapping_certificates",
        ),
        migrations.RemoveConstraint(
            model_name="certificatedescription",
            name="exclude_overlapping_certificate_descriptions",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=3,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]{3}$")],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="certificatedescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="certificatetype",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]{1}$")],
            ),
        ),
        migrations.AlterField(
            model_name="certificatetype",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
    ]
