# Generated by Django 3.0.11 on 2020-11-18 18:56
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_auto_20201117_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=3,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]{3}$")],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="certificatedescription",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="certificatedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="certificatetype",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]{1}$")],
            ),
        ),
        migrations.AlterField(
            model_name="certificatetype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
    ]
