# Generated by Django 3.1 on 2020-12-11 22:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0006_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificate",
            name="exclude_overlapping_certificates",
        ),
    ]
