# Generated by Django 3.0.10 on 2020-12-07 11:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0006_auto_20201201_1538"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificatedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificatedescription",
            name="exclude_overlapping_certificate_descriptions",
        ),
    ]
