# Generated by Django 3.1 on 2020-12-12 14:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0007_auto_20201211_2220"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificatedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="certificatedescription",
            name="exclude_overlapping_certificate_descriptions",
        ),
    ]
