# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0007_auto_20201207_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="certificatedescription",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="certificatetype",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
