# Generated by Django 3.1 on 2021-01-06 15:33
from decimal import Decimal

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models

import common.fields
import quotas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("measures", "0001_initial"),
        ("common", "0001_initial"),
        ("geo_areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaAssociation",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                (
                    "sub_quota_relation_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equivalent to main quota"),
                            ("NM", "Normal (restrictive to main quota)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("1.00000"),
                        max_digits=16,
                        validators=[quotas.validators.validate_coefficient],
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel",),
        ),
        migrations.CreateModel(
            name="QuotaDefinition",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                ("valid_between", common.fields.TaricDateTimeRangeField(db_index=True)),
                ("sid", common.fields.SignedIntSID()),
                ("volume", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "initial_volume",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "maximum_precision",
                    models.PositiveSmallIntegerField(
                        validators=[quotas.validators.validate_max_precision]
                    ),
                ),
                ("quota_critical", models.BooleanField(default=False)),
                (
                    "quota_critical_threshold",
                    models.PositiveSmallIntegerField(
                        validators=[quotas.validators.validate_percentage]
                    ),
                ),
                ("description", common.fields.ShortDescription()),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="measures.measurementunit",
                    ),
                ),
                (
                    "measurement_unit_qualifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="measures.measurementunitqualifier",
                    ),
                ),
                (
                    "monetary_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="measures.monetaryunit",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="QuotaOrderNumber",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                ("valid_between", common.fields.TaricDateTimeRangeField(db_index=True)),
                ("sid", common.fields.SignedIntSID()),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{6}$")
                        ],
                    ),
                ),
                (
                    "mechanism",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "First come, first served"), (1, "Licensed")]
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "WTO"),
                            (1, "Autonomous"),
                            (2, "Preferential"),
                            (3, "Safeguard"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="QuotaOrderNumberOrigin",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                ("valid_between", common.fields.TaricDateTimeRangeField(db_index=True)),
                ("sid", common.fields.SignedIntSID()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="QuotaSuspension",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                ("valid_between", common.fields.TaricDateTimeRangeField(db_index=True)),
                ("sid", common.fields.SignedIntSID()),
                ("description", common.fields.ShortDescription()),
                (
                    "quota_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quotas.quotadefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="QuotaOrderNumberOriginExclusion",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                (
                    "excluded_geographical_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geo_areas.geographicalarea",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quotas.quotaordernumberorigin",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel",),
        ),
        migrations.AddField(
            model_name="quotaordernumberorigin",
            name="excluded_areas",
            field=models.ManyToManyField(
                related_name="_quotaordernumberorigin_excluded_areas_+",
                through="quotas.QuotaOrderNumberOriginExclusion",
                to="geo_areas.GeographicalArea",
            ),
        ),
        migrations.AddField(
            model_name="quotaordernumberorigin",
            name="geographical_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="geo_areas.geographicalarea",
            ),
        ),
        migrations.AddField(
            model_name="quotaordernumberorigin",
            name="order_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="quotas.quotaordernumber",
            ),
        ),
        migrations.AddField(
            model_name="quotaordernumber",
            name="origins",
            field=models.ManyToManyField(
                related_name="quotas",
                through="quotas.QuotaOrderNumberOrigin",
                to="geo_areas.GeographicalArea",
            ),
        ),
        migrations.CreateModel(
            name="QuotaEvent",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                (
                    "subrecord_code",
                    models.CharField(
                        choices=[
                            ("00", "Quota balance event"),
                            ("05", "Quota unblocking event"),
                            ("10", "Quota critical state change event"),
                            ("15", "Quota exhaustion event"),
                            ("20", "Quota reopening event"),
                            ("25", "Quota unsuspension event"),
                            ("30", "Quota closed and balance transferred event"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("occurrence_timestamp", models.DateTimeField()),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "quota_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quotas.quotadefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel",),
        ),
        migrations.AddField(
            model_name="quotadefinition",
            name="order_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="quotas.quotaordernumber",
            ),
        ),
        migrations.AddField(
            model_name="quotadefinition",
            name="sub_quotas",
            field=models.ManyToManyField(
                related_name="_quotadefinition_sub_quotas_+",
                through="quotas.QuotaAssociation",
                to="quotas.QuotaDefinition",
            ),
        ),
        migrations.CreateModel(
            name="QuotaBlocking",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.trackedmodel",
                    ),
                ),
                ("valid_between", common.fields.TaricDateTimeRangeField(db_index=True)),
                ("sid", common.fields.SignedIntSID()),
                (
                    "blocking_period_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (
                                1,
                                "Block the allocations for a quota due to a late publication",
                            ),
                            (
                                2,
                                "Block the allocations for a quota after its reopening due to a volume increase",
                            ),
                            (
                                3,
                                "Block the allocations for a quota after its reopening due to the reception of quota return requests",
                            ),
                            (
                                4,
                                "Block the allocations for a quota due to the modification of the validity period after receiving quota return requests",
                            ),
                            (
                                5,
                                "Block the allocations for a quota on request of a MSA",
                            ),
                            (
                                6,
                                "Block the allocations for a quota due to an end user decision",
                            ),
                            (
                                7,
                                "Block the allocations for a quota due to an exceptional condition",
                            ),
                            (
                                8,
                                "Block the allocations for a quota after its reopening due to a balance transfer",
                            ),
                        ]
                    ),
                ),
                ("description", common.fields.ShortDescription()),
                (
                    "quota_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quotas.quotadefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.AddField(
            model_name="quotaassociation",
            name="main_quota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_quota_associations",
                to="quotas.quotadefinition",
            ),
        ),
        migrations.AddField(
            model_name="quotaassociation",
            name="sub_quota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="main_quota_associations",
                to="quotas.quotadefinition",
            ),
        ),
    ]
