# Generated by Django 3.1 on 2021-01-14 13:46
import django.core.serializers.json
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotaevent",
            name="data",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
