# Generated by Django 3.0.10 on 2020-10-18 08:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("measures", "0003_add_measures_data_model"),
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotadefinition",
            name="measurement_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.MeasurementUnit",
            ),
        ),
        migrations.AddField(
            model_name="quotadefinition",
            name="measurement_unit_qualifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.MeasurementUnitQualifier",
            ),
        ),
        migrations.AddField(
            model_name="quotadefinition",
            name="monetary_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="measures.MonetaryUnit",
            ),
        ),
    ]
