# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0002_link_to_measures_data_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotablocking",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="quotadefinition",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="quotaordernumber",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="quotaordernumberorigin",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="quotasuspension",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
    ]
