# Generated by Django 3.1 on 2020-12-29 11:47
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0003_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotablocking",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotadefinition",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaevent",
            name="subrecord_code",
            field=models.CharField(
                choices=[
                    ("00", "Quota balance event"),
                    ("05", "Quota unblocking event"),
                    ("10", "Quota critical state change event"),
                    ("15", "Quota exhaustion event"),
                    ("20", "Quota reopening event"),
                    ("25", "Quota unsuspension event"),
                    ("30", "Quota closed and balance transferred event"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="quotaordernumber",
            name="order_number",
            field=models.CharField(
                db_index=True,
                max_length=6,
                validators=[django.core.validators.RegexValidator("^[0-9]{6}$")],
            ),
        ),
        migrations.AlterField(
            model_name="quotaordernumber",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaordernumberorigin",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotasuspension",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
    ]
