# Generated by Django 3.0.11 on 2020-11-18 18:56
from django.db import migrations
from django.db import models

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0004_auto_20201117_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotablocking",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotablocking",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotadefinition",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotadefinition",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaevent",
            name="subrecord_code",
            field=models.CharField(
                choices=[
                    ("00", "Quota balance event"),
                    ("05", "Quota unblocking event"),
                    ("10", "Quota critical state change event"),
                    ("15", "Quota exhaustion event"),
                    ("20", "Quota reopening event"),
                    ("25", "Quota unsuspension event"),
                    ("30", "Quota closed and balance transferred event"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="quotaordernumber",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaordernumber",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaordernumberorigin",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotaordernumberorigin",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotasuspension",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="quotasuspension",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
    ]
