# Generated by Django 3.1.8 on 2021-05-06 15:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_auto_20210219_0955"),
        ("quotas", "0004_auto_20210317_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotaordernumber",
            name="required_certificates",
            field=models.ManyToManyField(
                related_name="quotas",
                to="certificates.Certificate",
            ),
        ),
    ]
