# Generated by Django 3.1 on 2020-12-01 10:30
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0005_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotaordernumber",
            name="order_number",
            field=models.CharField(
                db_index=True,
                max_length=6,
                validators=[django.core.validators.RegexValidator("^[0-9]{6}$")],
            ),
        ),
    ]
