# Generated by Django 3.2.20 on 2023-10-31 15:16

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quotas", "0007_auto_20221130_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotaordernumber",
            name="order_number",
            field=models.CharField(
                db_index=True,
                max_length=6,
                validators=[django.core.validators.RegexValidator("^05[0-9]{4}$")],
            ),
        ),
    ]
