# Generated by Django 4.2.10 on 2024-02-23 11:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_areas", "0006_alter_geographicalarea_memberships"),
        ("quotas", "0008_alter_quotaordernumber_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotadefinition",
            name="sub_quotas",
            field=models.ManyToManyField(
                through="quotas.QuotaAssociation",
                to="quotas.quotadefinition",
            ),
        ),
        migrations.AlterField(
            model_name="quotaordernumberorigin",
            name="excluded_areas",
            field=models.ManyToManyField(
                related_name="+",
                through="quotas.QuotaOrderNumberOriginExclusion",
                to="geo_areas.geographicalarea",
            ),
        ),
    ]
