# Generated by Django 4.2.14 on 2024-08-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_user_sso_uuid"),
        ("quotas", "0009_alter_quotadefinition_sub_quotas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaDefinitionDuplicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition_data", models.JSONField()),
                (
                    "current_transaction",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="definition_duplication",
                        to="common.transaction",
                    ),
                ),
                (
                    "main_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotas.quotadefinition",
                    ),
                ),
            ],
        ),
    ]
