# Generated by Django 3.1 on 2021-01-06 15:33
import django.db.models.deletion
from django.db import migrations
from django.db import models

import taric.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("envelope_id", taric.models.EnvelopeId(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnvelopeTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taric.envelope",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="envelope",
            name="transactions",
            field=models.ManyToManyField(
                related_name="envelopes",
                through="taric.EnvelopeTransaction",
                to="common.Transaction",
            ),
        ),
    ]
