# Generated by Django 3.0.10 on 2020-11-06 15:21
import django.db.models.deletion
from django.db import migrations
from django.db import models

import taric.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("envelope_id", taric.models.EnvelopeId()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnvelopeTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="taric.Envelope"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="taric.Transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="envelope",
            name="transactions",
            field=models.ManyToManyField(
                related_name="envelopes",
                through="taric.EnvelopeTransaction",
                to="taric.Transaction",
            ),
        ),
    ]
