# Generated by Django 3.0.10 on 2020-11-13 17:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taric", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="envelopetransaction",
            name="envelope",
        ),
        migrations.RemoveField(
            model_name="envelopetransaction",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="Envelope",
        ),
        migrations.DeleteModel(
            name="EnvelopeTransaction",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
