# Generated by Django 3.1.6 on 2021-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taric", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="envelope",
            options={"ordering": ("envelope_id",)},
        ),
    ]
