# Generated by Django 3.1 on 2020-12-26 10:01
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20201226_1001"),
        ("taric", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="envelopetransaction",
            options={"ordering": ("order",)},
        ),
        migrations.RenameField(
            model_name="envelopetransaction",
            old_name="index",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="envelope",
            name="transactions",
            field=models.ManyToManyField(
                related_name="envelopes",
                through="taric.EnvelopeTransaction",
                to="common.Transaction",
            ),
        ),
        migrations.AlterField(
            model_name="envelopetransaction",
            name="envelope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taric.envelope"
            ),
        ),
        migrations.AlterField(
            model_name="envelopetransaction",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.transaction"
            ),
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
