# Generated by Django 3.1 on 2021-01-02 08:36
from django.db import migrations

import taric.models


class Migration(migrations.Migration):

    dependencies = [
        ("taric", "0002_auto_20201226_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envelope",
            name="envelope_id",
            field=taric.models.EnvelopeId(unique=True),
        ),
    ]
