# Generated by Django 3.2.23 on 2024-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_create_custom_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EUDataModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workbasket_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
    ]
