# Generated by Django 3.2.23 on 2024-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_eudatamodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eudatamodel",
            name="date",
        ),
        migrations.RemoveField(
            model_name="eudatamodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="eudatamodel",
            name="workbasket_id",
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="add_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="duty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="geographical_area_exists",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="goods_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="goods_nomenclature_exists",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="legal_base",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="meas_type_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="measure_exists",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="measure_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="measure_type_exists",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="order_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="origin_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="red_ind",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eudatamodel",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
