# Generated by Django 3.1.14 on 2022-04-17 10:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0005_transaction_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("successful", models.BooleanField(null=True)),
                ("tracked_model_count", models.PositiveSmallIntegerField()),
                (
                    "head_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.transaction",
                    ),
                ),
                (
                    "latest_tracked_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.trackedmodel",
                        null=True,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="common.transaction",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "transaction__partition",
                    "transaction__order",
                    "head_transaction__partition",
                    "head_transaction__order",
                ),
            },
        ),
        migrations.CreateModel(
            name="TrackedModelCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_name", models.CharField(max_length=255)),
                ("successful", models.BooleanField()),
                ("message", models.TextField(null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="common.trackedmodel",
                    ),
                ),
                (
                    "transaction_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_checks",
                        to="checks.transactioncheck",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="transactioncheck",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("completed", False), ("successful__isnull", True)),
                    models.Q(("completed", True), ("successful__isnull", False)),
                    _connector="OR",
                ),
                name="completed_checks_include_successfulness",
            ),
        ),
    ]
