# Generated by Django 3.1.14 on 2022-05-17 13:31

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedmodelcheck",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trackedmodelcheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transactioncheck",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactioncheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
