# Generated by Django 3.1.14 on 2022-05-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0002_auto_20220517_1331"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transactioncheck",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transactioncheck",
            name="updated_at",
        ),
    ]
