# Generated by Django 3.1.14 on 2022-07-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_auto_20220525_1046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactioncheck",
            name="head_transaction",
        ),
        migrations.RemoveField(
            model_name="transactioncheck",
            name="latest_tracked_model",
        ),
        migrations.RemoveField(
            model_name="transactioncheck",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="TrackedModelCheck",
        ),
        migrations.DeleteModel(
            name="TransactionCheck",
        ),
    ]
