# Generated by Django 3.1.14 on 2022-08-02 20:32

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0006_modelcelerytask_taskmodel"),
        ("checks", "0004_auto_20220718_1653"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedModelCheck",
            fields=[
                (
                    "taskmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.taskmodel",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_name", models.CharField(max_length=255)),
                ("successful", models.BooleanField()),
                ("message", models.TextField(null=True)),
                ("content_hash", models.BinaryField(max_length=32, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="common.trackedmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("model", "check_name")},
            },
            bases=("common.taskmodel", models.Model),
        ),
    ]
