# Generated by Django 3.2.23 on 2023-12-11 16:42

import django.utils.timezone
from django.db import migrations
from django.db import models

epoch_time = 0000000000


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0005_trackedmodelcheck_processing_time"),
        ("common", "0009_set_tracked_model_datetime"),
        ("workbaskets", "0008_datarow_dataupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactioncheck",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.datetime.fromtimestamp(epoch_time),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactioncheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
