# Generated by Django 3.1.14 on 2022-08-23 23:19

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_modelcelerytask_taskmodel"),
        ("checks", "0005_trackedmodelcheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRuleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("current", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="trackedmodelcheck",
            name="head_transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.transaction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trackedmodelcheck",
            name="model",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks",
                to="common.trackedmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackedmodelcheck",
            unique_together={("model", "head_transaction")},
        ),
        migrations.CreateModel(
            name="BusinessRuleResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Passed"), (2, "Failed"), (3, "Error")],
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="checks.businessrulemodel",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="check_name",
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="message",
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="successful",
        ),
        migrations.RemoveField(
            model_name="trackedmodelcheck",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="trackedmodelcheck",
            name="results",
            field=models.ManyToManyField(to="checks.BusinessRuleResult"),
        ),
    ]
