# Generated by Django 4.2.10 on 2024-03-21 18:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0007_transactioncheck_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedmodelcheck",
            name="processing_time",
            field=models.FloatField(null=True),
        ),
    ]
