# Generated by Django 4.2.16 on 2024-12-12 15:14

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0013_alter_goodsnomenclature_origins_and_more"),
        ("workbaskets", "0009_workbasket_missing_measures_check_task_id"),
        ("checks", "0008_alter_trackedmodelcheck_processing_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingMeasuresCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("successful", models.BooleanField(null=True)),
                (
                    "workbasket",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missing_measures_check",
                        to="workbaskets.workbasket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissingMeasureCommCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commodities.goodsnomenclature",
                    ),
                ),
                (
                    "missing_measures_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_checks",
                        to="checks.missingmeasurescheck",
                    ),
                ),
            ],
        ),
    ]
