# Generated by Django 4.2.17 on 2025-01-22 16:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0009_missingmeasurescheck_missingmeasurecommcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingmeasurescheck",
            name="hash",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
