# Generated by Django 4.2.18 on 2025-02-04 16:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0009_missingmeasurescheck_missingmeasurecommcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingmeasurecommcode",
            name="successful",
            field=models.BooleanField(null=True),
        ),
    ]
