# Generated by Django 4.2.18 on 2025-02-11 16:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0010_missingmeasurecommcode_successful"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingmeasurescheck",
            name="hash",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
