# Generated by Django 3.1 on 2020-12-09 15:06
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ImporterXMLChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_code", models.CharField(blank=True, max_length=3, null=True)),
                ("chapter", models.CharField(blank=True, max_length=2, null=True)),
                ("chunk_number", models.PositiveSmallIntegerField()),
                ("chunk_text", models.TextField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="importer.importbatch",
                    ),
                ),
            ],
        ),
    ]
