# Generated by Django 3.1 on 2020-12-29 14:34
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importbatch",
            name="split_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="importerxmlchunk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importerxmlchunk",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "WAITING"), (2, "RUNNING"), (3, "DONE"), (4, "ERRORED")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="importerxmlchunk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chunks",
                to="importer.importbatch",
            ),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="chapter",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="record_code",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
