# Generated by Django 3.1 on 2020-12-09 15:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importerxmlchunk",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "WAITING"), (2, "RUNNING"), (3, "DONE"), (4, "ERRORED")],
                default=1,
            ),
        ),
    ]
