# Generated by Django 3.1 on 2021-01-01 17:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0002_auto_20201229_1434"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchDependencies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependent_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_dependencies",
                        to="importer.importbatch",
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_dependents",
                        to="importer.importbatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="importbatch",
            name="dependencies",
            field=models.ManyToManyField(
                through="importer.BatchDependencies", to="importer.ImportBatch"
            ),
        ),
    ]
