# Generated by Django 3.1 on 2020-12-19 15:48
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0002_auto_20201217_1403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chunks",
                to="importer.importbatch",
            ),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="chapter",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="importerxmlchunk",
            name="record_code",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
