# Generated by Django 3.2.18 on 2023-03-17 08:39

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0003_auto_20210302_1349"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImporterError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Error"), (2, "Warning"), (3, "Information")],
                        default=1,
                    ),
                ),
                ("description", models.TextField()),
                ("object_type", models.TextField()),
                ("object_identity_keys", models.TextField()),
                ("related_object_type", models.TextField()),
                ("related_object_identity_keys", models.TextField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errors",
                        to="importer.importbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
