# Generated by Django 3.1.6 on 2021-03-02 13:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_auto_20210302_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="failure_details",
            field=models.TextField(blank=True),
        ),
    ]
