# Generated by Django 3.2.18 on 2023-04-18 13:47

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0004_importbatch_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("IMPORTING", "Importing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="IMPORTING",
                editable=False,
                max_length=50,
            ),
        ),
    ]
