# Generated by Django 3.2.19 on 2023-06-19 17:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workbaskets", "0007_alter_workbasket_options"),
        ("importer", "0006_calculate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="workbasket",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workbaskets.workbasket",
            ),
        ),
    ]
