# Generated by Django 3.2.19 on 2023-06-29 11:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0008_importbatch_taric_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
