# Generated by Django 3.2.19 on 2023-06-30 11:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0009_alter_importbatch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
