# Generated by Django 3.2.19 on 2023-08-08 15:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0010_alter_importbatch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="goods_import",
            field=models.BooleanField(default=False),
        ),
    ]
