# Generated by Django 3.2.19 on 2023-09-18 14:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0011_importbatch_goods_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchImportError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_type", models.CharField(max_length=250)),
                ("related_object_type", models.CharField(max_length=250)),
                ("related_object_identity_keys", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=2000)),
                ("issue_type", models.CharField(max_length=2000)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="importer.importbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
