# Generated by Django 3.2.19 on 2023-09-19 09:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0012_batchimporterror"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchimporterror",
            name="change_type",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="batchimporterror",
            name="object_details",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="batchimporterror",
            name="transaction_id",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
