# Generated by Django 3.2.23 on 2024-01-10 09:52

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0012_batchimporterror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("IMPORTING", "Importing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("FAILED_EMPTY", "Failed Empty"),
                ],
                db_index=True,
                default="IMPORTING",
                editable=False,
                max_length=50,
            ),
        ),
    ]
