# Generated by Django 4.2.20 on 2025-04-30 17:24

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0024_alter_tasktemplate_automation_class_name"),
        ("importer", "0013_alter_importbatch_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportGoodsAutomation",
            fields=[
                (
                    "automation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.automation",
                    ),
                ),
                (
                    "import_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="importer.importbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tasks.automation",),
        ),
    ]
