# Generated by Django 3.2.19 on 2023-09-19 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0013_auto_20230919_1018"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batchimporterror",
            old_name="change_type",
            new_name="taric_change_type",
        ),
    ]
