# Generated by Django 3.2.23 on 2023-11-13 08:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0014_rename_change_type_batchimporterror_taric_change_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchimporterror",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("ERROR", "Error"),
                    ("WARNING", "warning"),
                    ("INFORMATION", "Information"),
                ],
                max_length=2000,
            ),
        ),
    ]
