# Generated by Django 3.1.14 on 2022-09-04 20:38

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workbaskets", "0004_archive_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("envelope_id", models.CharField(max_length=10)),
                ("xml_file", models.FileField(null=True, upload_to="")),
                ("cds_report_file", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="PackagedWorkBasket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        verbose_name="order",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Awaiting processing"),
                            ("CP", "Currently processing"),
                            ("SP", "Successfully processed"),
                            ("FP", "Failed processing"),
                        ],
                        default="AP",
                        max_length=2,
                    ),
                ),
                (
                    "envelope",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packaging.envelope",
                    ),
                ),
                (
                    "workbasket",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workbaskets.workbasket",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
