# Generated by Django 4.2.15 on 2024-10-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql=[("CREATE SCHEMA reporting;")],
            reverse_sql=[("DROP SCHEMA reporting;")],
        ),
    ]
