# Generated by Django 4.2.15 on 2024-10-14 16:10

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalCodeDescriptionLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("validity_start", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalCodeLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                ("code", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalCodeTypeLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.CharField(max_length=1)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("application_code", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CertificateDescriptionLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("validity_start", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CertificateLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="CertificateTypeLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.CharField(max_length=1)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootnoteAssociationGoodsNomenclatureLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureDescriptionLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("validity_start", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureIndentLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                ("indent", models.IntegerField()),
                ("validity_start", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sid", models.IntegerField()),
                ("item_id", models.CharField(max_length=10)),
                ("suffix", models.CharField(max_length=2)),
                ("statistical", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclaturelatest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureOriginLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "derived_from_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclaturelookup",
                    ),
                ),
                (
                    "new_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="commoditiesgoodsnomenclatureorigin_new_goods_nomenclature_set",
                        to="open_data.goodsnomenclaturelookup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureSuccessorLatest",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "absorbed_into_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclaturelookup",
                    ),
                ),
                (
                    "replaced_goods_nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="commoditiesgoodsnomenclaturesuccessor_replaced_goods_nomenclature_set",
                        to="open_data.goodsnomenclaturelookup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureSuccessorLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclaturesuccessorlatest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureOriginLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclatureoriginlatest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureIndentLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclatureindentlatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goodsnomenclatureindentlatest",
            name="indented_goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.goodsnomenclaturelookup",
            ),
        ),
        migrations.CreateModel(
            name="GoodsNomenclatureDescriptionLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.goodsnomenclaturedescriptionlatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goodsnomenclaturedescriptionlatest",
            name="described_goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.goodsnomenclaturelookup",
            ),
        ),
        migrations.CreateModel(
            name="FootnoteAssociationGoodsNomenclatureLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.footnoteassociationgoodsnomenclaturelatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="footnoteassociationgoodsnomenclaturelatest",
            name="goods_nomenclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.goodsnomenclaturelookup",
            ),
        ),
        migrations.CreateModel(
            name="CertificateTypeLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.certificatetypelatest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.certificatelatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="certificatelatest",
            name="certificate_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.certificatetypelookup",
            ),
        ),
        migrations.CreateModel(
            name="CertificateDescriptionLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.certificatedescriptionlatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="certificatedescriptionlatest",
            name="described_certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.certificatelookup",
            ),
        ),
        migrations.CreateModel(
            name="AdditionalCodeTypeLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.additionalcodetypelatest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalCodeLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.additionalcodelatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalcodelatest",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.additionalcodetypelookup",
            ),
        ),
        migrations.CreateModel(
            name="AdditionalCodeDescriptionLookUp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="open_data.additionalcodedescriptionlatest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalcodedescriptionlatest",
            name="described_additionalcode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.additionalcodelookup",
            ),
        ),
    ]
