# Generated by Django 4.2.15 on 2024-10-30 11:07

from django.db import migrations

from open_data.models.utils import schema_required


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0013_versiongroup_common_vers_current_04c358_idx"),
    ]
    if schema_required():
        operations = [
            migrations.RunSQL(
                sql=[("CREATE SCHEMA reporting;")],
                reverse_sql=[("DROP SCHEMA reporting;")],
            ),
        ]
    else:
        operations = []
