# Generated by Django 4.2.15 on 2024-10-30 11:07

from django.db import migrations


def forwards(apps, schema_editor):
    if schema_editor.connection.vendorstartswith("postgres"):
        print("In POSTGRES")
        try:
            schema_editor.execute("CREATE SCHEMA reporting;")
        except:
            print(f"ERROR: {schema_editor.connection.alias=}")


def backwards(apps, schema_editor):
    if schema_editor.connection.vendor.startswith("postgres"):
        schema_editor.execute("DROP SCHEMA reporting;")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
