# Generated by Django 4.2.15 on 2024-10-30 11:07

from django.db import migrations

from open_data.models.utils import migrate_to_postgres


class Migration(migrations.Migration):
    initial = True

    dependencies = []
    if migrate_to_postgres():
        operations = [
            migrations.RunSQL(
                sql=[("CREATE ASCHEMA reporting;")],
                reverse_sql=[("DROP SCHEMA reporting;")],
            ),
        ]
    else:
        operations = []
