# Generated by Django 4.2.15 on 2024-10-30 11:33

from django.db import migrations

create_view_sql = """
CREATE MATERIALIZED VIEW foreign_key_lookup AS
	SELECT  common_trackedmodel.ID as old_id, current_version_id
	FROM public.common_trackedmodel
 	INNER JOIN common_versiongroup
		ON (common_trackedmodel.version_group_id = common_versiongroup.id)
WHERE (current_version_id IS NOT NULL AND NOT (common_trackedmodel.update_type = 2));

CREATE UNIQUE INDEX old_id_idx ON foreign_key_lookup (old_id);
CREATE INDEX current_version_id_idx ON foreign_key_lookup (current_version_id);
"""


def forwards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgres":
        try:
            schema_editor.execute(create_view_sql)
        except:
            print(f"ERROR: Not Postgres database")


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0002_drop_fk_constrains"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
