# Generated by Django 4.2.15 on 2024-10-30 11:17

from django.db import migrations

drop_fk_sql = """
DO $$DECLARE r record;
    BEGIN
        FOR r IN SELECT table_schema, table_name, constraint_name
				FROM information_schema.table_constraints AS tc 
				WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema='reporting'

        LOOP
            EXECUTE 'ALTER TABLE '|| quote_ident(r.table_schema) || '.' || quote_ident(r.table_name)|| ' DROP CONSTRAINT '|| quote_ident(r.constraint_name) || ';';
        END LOOP;
    END$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(drop_fk_sql),
    ]
