# Generated by Django 4.2.15 on 2024-10-30 11:33

from django.db import migrations

from open_data.direct_sql import get_create_materialised_view_sql
from open_data.models.utils import in_sqlite


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0003_drop_fk_constrains"),
    ]
    if not in_sqlite():

        operations = [
            migrations.RunSQL(get_create_materialised_view_sql()),
        ]
    else:
        operations = []
