# Generated by Django 4.2.16 on 2025-03-28 12:10

from django.db import migrations
from django.db import models

from open_data.models.utils import schema_required


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0004_materialised_view"),
    ]

    if schema_required():
        schema_name = 'reporting"."'
    else:
        schema_name = ""

    operations = [
        migrations.CreateModel(
            name="ReportCommodityReport",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commodity_sid", models.IntegerField()),
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "commodity_suffix",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("commodity_description", models.TextField(blank=True, null=True)),
                ("commodity_validity_start", models.DateField()),
                ("commodity_validity_end", models.DateField(blank=True, null=True)),
                ("parent_sid", models.IntegerField(blank=True, null=True)),
                ("parent_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "parent_suffix",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
            ],
            options={
                "db_table": f"{schema_name}open_data_reportcommodityreport",
            },
        ),
    ]
