# Generated by Django 4.2.15 on 2024-11-25 15:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0004_materialised_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGoodsNomenclatureParentTemp",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.IntegerField(
                        db_column="trackedmodel_ptr_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sid", models.IntegerField()),
                ("item_id", models.CharField(max_length=10)),
                ("indent", models.IntegerField()),
                ("suffix", models.CharField(max_length=2)),
                ("parent_trackedmodel_ptr_id", models.IntegerField(null=True)),
                ("parent_sid", models.IntegerField(null=True)),
                (
                    "parent_item_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": 'reporting"."open_data_reportreportgoodsnomenclatureparenttemp',
            },
        ),
        migrations.AddField(
            model_name="reportgoodsnomenclature",
            name="parent_trackedmodel_ptr",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="reportgeographicalareadescription",
            name="described_geographicalarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="descriptions",
                to="open_data.reportgeographicalarea",
            ),
        ),
    ]
