# Generated by Django 4.2.15 on 2024-12-12 11:25

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0004_materialised_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportgoodsnomenclatureindent",
            name="indented_goods_nomenclature",
        ),
        migrations.AddField(
            model_name="reportgoodsnomenclature",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportgoodsnomenclature",
            name="indent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="reportgoodsnomenclature",
            name="parent_trackedmodel_ptr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.reportgoodsnomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="reportgeographicalareadescription",
            name="described_geographicalarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="descriptions",
                to="open_data.reportgeographicalarea",
            ),
        ),
        migrations.DeleteModel(
            name="ReportGoodsNomenclatureDescription",
        ),
        migrations.DeleteModel(
            name="ReportGoodsNomenclatureIndent",
        ),
    ]
