# Generated by Django 4.2.16 on 2025-03-26 10:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0004_materialised_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDateStamp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("Refresh", "Refresh open data"),
                            ("Export", "Export open data"),
                        ],
                    ),
                ),
                ("event_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("Command", "Management command"),
                            ("", "Async process"),
                            ("2", "Test"),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": 'reporting"."open_data_reportdatestamp',
            },
        ),
    ]
