# Generated by Django 4.2.15 on 2024-12-13 10:40

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0006_alter_geographicalarea_memberships"),
        (
            "open_data",
            "0005_remove_reportgoodsnomenclatureindent_indented_goods_nomenclature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportgeographicalarea",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="reportgeographicalarea",
            name="is_all_countries",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportgeographicalarea",
            name="is_group",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportgeographicalarea",
            name="is_single_region_or_country",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportgeographicalarea",
            name="trackedmodel_ptr",
            field=models.ForeignKey(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="geo_areas.geographicalarea",
            ),
        ),
    ]
