# Generated by Django 4.2.16 on 2025-04-01 15:25

from django.db import migrations
from django.db import models

from open_data.models.utils import schema_required


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0005_reportcommodityreport"),
    ]

    if schema_required():
        schema_name = 'reporting"."'
    else:
        schema_name = ""

    operations = [
        migrations.CreateModel(
            name="ReportMeasureAsDefinedReport",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=None,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("trackedmodel_ptr_id", models.IntegerField()),
                ("commodity_sid", models.IntegerField(blank=True)),
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("commodity_indent", models.IntegerField(null=True)),
                ("commodity_description", models.TextField(blank=True, null=True)),
                ("measure_sid", models.IntegerField(blank=True)),
                ("measure_type_id", models.CharField(max_length=6)),
                ("measure_type_description", models.TextField(blank=True, null=True)),
                (
                    "measure_additional_code_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "measure_additional_code_description",
                    models.TextField(blank=True, null=True),
                ),
                ("measure_duty_expression", models.TextField(blank=True, null=True)),
                ("measure_effective_start_date", models.DateField()),
                ("measure_effective_end_date", models.DateField(blank=True, null=True)),
                (
                    "measure_reduction_indicator",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("measure_footnotes", models.TextField(blank=True, null=True)),
                ("measure_conditions", models.TextField(blank=True, null=True)),
                ("measure_geographical_area_sid", models.IntegerField(null=True)),
                ("measure_geographical_area_id", models.CharField(max_length=4)),
                (
                    "measure_geographical_area_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "measure_excluded_geographical_areas_ids",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "measure_excluded_geographical_areas_descriptions",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "measure_quota_order_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "measure_regulation_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "measure_regulation_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": f"{schema_name}open_data_reportmeasureasdefinedreport",
            },
        ),
    ]
