# Generated by Django 4.2.15 on 2024-11-25 15:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0005_reportgoodsnomenclatureparenttemp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportgoodsnomenclature",
            name="indent",
            field=models.IntegerField(null=True),
        ),
    ]
