# Generated by Django 4.2.15 on 2024-11-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0006_reportgoodsnomenclature_indent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportGoodsNomenclatureParentTemp",
        ),
    ]
