# Generated by Django 4.2.16 on 2024-12-16 13:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0006_allow_blank_descriptions"),
        ("additional_codes", "0007_allow_blank_descriptions"),
        ("commodities", "0013_alter_goodsnomenclature_origins_and_more"),
        ("certificates", "0004_validity_start"),
        ("open_data", "0006_reportgeographicalarea_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcertificatedescription",
            name="described_certificate",
        ),
        migrations.RemoveField(
            model_name="reportfootnotedescription",
            name="described_footnote",
        ),
        migrations.RemoveField(
            model_name="reportgeographicalareadescription",
            name="described_geographicalarea",
        ),
        migrations.AddField(
            model_name="reportadditionalcode",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportcertificate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportfootnote",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportadditionalcode",
            name="trackedmodel_ptr",
            field=models.ForeignKey(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="additional_codes.additionalcode",
            ),
        ),
        migrations.AlterField(
            model_name="reportcertificate",
            name="trackedmodel_ptr",
            field=models.ForeignKey(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="certificates.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="reportfootnote",
            name="trackedmodel_ptr",
            field=models.ForeignKey(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="footnotes.footnote",
            ),
        ),
        migrations.AlterField(
            model_name="reportgoodsnomenclature",
            name="trackedmodel_ptr",
            field=models.ForeignKey(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="commodities.goodsnomenclature",
            ),
        ),
        migrations.DeleteModel(
            name="ReportAdditionalCodeDescription",
        ),
        migrations.DeleteModel(
            name="ReportCertificateDescription",
        ),
        migrations.DeleteModel(
            name="ReportFootnoteDescription",
        ),
        migrations.DeleteModel(
            name="ReportGeographicalAreaDescription",
        ),
    ]
