# Generated by Django 4.2.15 on 2024-11-26 09:57

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0007_delete_reportgoodsnomenclatureparenttemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportgoodsnomenclature",
            name="parent_trackedmodel_ptr_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="open_data.reportgoodsnomenclature",
            ),
        ),
    ]
