# Generated by Django 4.2.16 on 2024-12-16 13:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "regulations",
            "0010_alter_regulation_amends_alter_regulation_extends_and_more",
        ),
        ("open_data", "0008_alter_reportadditionalcodetype_trackedmodel_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportreplacement",
            name="trackedmodel_ptr",
            field=models.OneToOneField(
                db_column="trackedmodel_ptr_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="regulations.replacement",
            ),
        ),
    ]
