# Generated by Django 4.2.16 on 2024-12-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0008_reportmeasurecondition_reference_price_string_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportmeasurecondition",
            old_name="reference_price_string",
            new_name="duty_sentence",
        ),
    ]
