# Generated by Django 4.2.16 on 2024-12-23 13:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_data",
            "0009_rename_reference_price_string_reportmeasurecondition_duty_sentence",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportmeasure",
            name="duty_sentence",
            field=models.TextField(blank=True, null=True),
        ),
    ]
