# Generated by Django 4.2.16 on 2024-12-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_data", "0010_reportmeasure_duty_sentence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportmeasure",
            old_name="duty_sentence",
            new_name="reference_price",
        ),
    ]
