# Generated by Django 4.2.14 on 2024-09-05 14:06

from django.conf import settings
from django.db import migrations
from django.db import models


def forwards_delete_outdated_permissions(apps, schema_editor):
    """Deletes old set of permissions belonging to `UserAssignment` following
    the renaming to `TaskAssignee` as Django creates a new set of permissions
    for the renamed table."""
    Permission = apps.get_model("auth.Permission")
    Permission.objects.filter(
        models.Q(codename="add_userassignment")
        | models.Q(codename="change_userassignment")
        | models.Q(codename="delete_userassignment")
        | models.Q(codename="view_userassignment"),
    ).delete()


def backwards_delete_outdated_permissions(apps, schema_editor):
    """Deletes old set of permissions belonging to `TaskAssignee` following the
    renaming back to `UserAssignment` as Django creates a new set of permissions
    for the renamed table."""
    Permission = apps.get_model("auth.Permission")
    Permission.objects.filter(
        models.Q(codename="add_taskassignee")
        | models.Q(codename="change_taskassignee")
        | models.Q(codename="delete_taskassignee")
        | models.Q(codename="view_taskassignee"),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAssignment",
            new_name="TaskAssignee",
        ),
        migrations.AlterField(
            model_name="taskassignee",
            name="task",
            field=models.ForeignKey(
                editable=False,
                on_delete=models.deletion.CASCADE,
                related_name="assignees",
                to="tasks.task",
            ),
        ),
        migrations.RunPython(
            forwards_delete_outdated_permissions,
            backwards_delete_outdated_permissions,
        ),
    ]
