# Generated by Django 4.2.14 on 2024-09-06 14:33

import django.db.models.deletion
from django.db import migrations
from django.db import models

from tasks.models import ProgressState as TaskProgressState
from workbaskets.validators import WorkflowStatus


def forwards_create_default_task_progress_state_instances(apps, schema_editor):
    """Creates default `ProgressState` instances for `TO_DO`, `IN_PROGRESS` and
    `DONE`."""
    ProgressState = apps.get_model("tasks", "ProgressState")
    progress_states = [ProgressState(name=state) for state in TaskProgressState.State]
    ProgressState.objects.bulk_create(progress_states)


def forwards_update_existing_tasks_progress_state(apps, schema_editor):
    """
    Updates `progress_state` on existing `Task` instances that have an
    associated workbasket.

    Tasks with an unpublished workbasket are set to `ProgressState.State.IN_PROGRESS`
    and tasks with a published workbasket are set to `ProgressState.State.DONE`.
    """
    ProgressState = apps.get_model("tasks", "ProgressState")
    inprogress_state = ProgressState.objects.get(
        name=TaskProgressState.State.IN_PROGRESS,
    )
    done_state = ProgressState.objects.get(name=TaskProgressState.State.DONE)
    Task = apps.get_model("tasks", "Task")

    Task.objects.filter(
        models.Q(workbasket__status=WorkflowStatus.EDITING)
        | models.Q(workbasket__status=WorkflowStatus.QUEUED)
        | models.Q(workbasket__status=WorkflowStatus.ERRORED),
    ).update(progress_state=inprogress_state)

    Task.objects.filter(
        models.Q(workbasket__status=WorkflowStatus.PUBLISHED)
        | models.Q(workbasket__status=WorkflowStatus.ARCHIVED),
    ).update(progress_state=done_state)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_userassignment_taskassignee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProgressState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TO_DO", "To do"),
                            ("IN_PROGRESS", "In progress"),
                            ("DONE", "Done"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            forwards_create_default_task_progress_state_instances,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.category",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.progressstate",
            ),
        ),
        migrations.RunPython(
            forwards_update_existing_tasks_progress_state,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="task",
            name="progress_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.progressstate",
            ),
        ),
    ]
