# Generated by Django 4.2.14 on 2024-09-06 14:33

import django.db.models.deletion
from django.db import migrations
from django.db import models


def forwards_create_default_progress_states(apps, schema_editor):
    TaskProgressState = apps.get_model("tasks", "TaskProgressState")
    defaults = ["To do", "In progress", "Done"]
    progress_states = [TaskProgressState(name=state) for state in defaults]
    TaskProgressState.objects.bulk_create(progress_states)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_userassignment_taskassignee"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "task categories",
            },
        ),
        migrations.CreateModel(
            name="TaskProgressState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.taskcategory",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.taskprogressstate",
            ),
        ),
        migrations.RunPython(
            forwards_create_default_progress_states,
            migrations.RunPython.noop,
        ),
    ]
