# Generated by Django 4.2.14 on 2024-09-09 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0006_task_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskassignee",
            name="assigned_by",
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_UNASSIGNED", "Task Unassigned"),
                            ("PROGRESS_STATE_UPDATED", "Progress State Updated"),
                        ],
                        editable=False,
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(editable=False)),
                (
                    "instigator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
