# Generated by Django 4.2.14 on 2024-09-10 18:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0008_datarow_dataupload"),
        ("tasks", "0007_create_tasklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="workbasket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="workbaskets.workbasket",
            ),
        ),
    ]
