# Generated by Django 4.2.16 on 2024-11-12 15:08

import django.db.models.deletion
from django.db import migrations
from django.db import models

import tasks.models.task


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_taskworkflowtemplate_taskworkflow_tasktemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress_state",
            field=models.ForeignKey(
                default=tasks.models.task.ProgressState.get_default_state_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.progressstate",
            ),
        ),
    ]
