# Generated by Django 4.2.16 on 2024-11-20 17:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_task_progress_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskworkflow",
            name="summary_task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.task",
            ),
        ),
    ]
