# Generated by Django 4.2.16 on 2024-11-20 17:27

from django.db import migrations


def assign_new_summary_task_on_workflow(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    TaskWorkflow = apps.get_model("tasks", "TaskWorkflow")

    for task_workflow in TaskWorkflow.objects.all():
        task_workflow.summary_task = Task.objects.create(
            title="Workflow summarising task",
            description="Workflow summarising task.",
        )
        TaskWorkflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_taskworkflow_summary_task"),
    ]

    operations = []
    operations = [migrations.RunPython(assign_new_summary_task_on_workflow)]
