# Generated by Django 4.2.16 on 2024-11-20 17:31

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_taskworkflow_assign_summary_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskworkflow",
            name="summary_task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.task",
            ),
        ),
    ]
