# Generated by Django 4.2.16 on 2024-11-20 17:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_alter_taskworkflow_summary_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskworkflow",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taskworkflow",
            name="title",
        ),
        migrations.AlterField(
            model_name="taskworkflowtemplate",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of what this workflow template is used for. ",
            ),
        ),
    ]
