# Generated by Django 4.2.15 on 2024-11-28 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0014_remove_taskworkflow_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskworkflowtemplate",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_taskworkflowtemplates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
