# Generated by Django 4.2.15 on 2024-11-29 15:48

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_taskworkflow_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskitem",
            old_name="queue",
            new_name="workflow",
        ),
        migrations.AlterField(
            model_name="taskitem",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_items",
                to="tasks.taskworkflow",
            ),
        ),
        migrations.AlterModelOptions(
            name="taskitem",
            options={"ordering": ["workflow", "position"]},
        ),
        migrations.RenameField(
            model_name="taskitemtemplate",
            old_name="queue",
            new_name="workflow_template",
        ),
        migrations.AlterField(
            model_name="taskitemtemplate",
            name="workflow_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_template_items",
                to="tasks.taskworkflowtemplate",
            ),
        ),
        migrations.AlterModelOptions(
            name="taskitemtemplate",
            options={"ordering": ["workflow_template", "position"]},
        ),
    ]
