# Generated by Django 4.2.15 on 2024-12-09 14:53

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_rename_queue_taskitem_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskworkflowtemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskworkflowtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
