# Generated by Django 4.2.17 on 2024-12-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_taskworkflowtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="tasktemplate",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="taskworkflow",
            options={"ordering": ["id"], "verbose_name": "workflow"},
        ),
        migrations.AlterModelOptions(
            name="taskworkflowtemplate",
            options={"ordering": ["id"], "verbose_name": "workflow template"},
        ),
    ]
