# Generated by Django 4.2.17 on 2024-12-23 14:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_alter_task_options_alter_tasktemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignee",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("WORKBASKET_WORKER", "Workbasket worker"),
                    ("WORKBASKET_REVIEWER", "Workbasket reviewer"),
                    ("GENERAL", "General"),
                ],
                max_length=50,
            ),
        ),
    ]
