# Generated by Django 4.2.18 on 2025-03-03 10:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_alter_taskassignee_assignment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskworkflow",
            name="eif_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskworkflow",
            name="policy_contact",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
