# Generated by Django 4.2.18 on 2025-04-10 11:54

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_taskworkflow_eif_date_taskworkflow_policy_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress_state",
            field=django_fsm.FSMField(
                choices=[
                    ("TO_DO", "To do"),
                    ("IN_PROGRESS", "In progress"),
                    ("DONE", "Done"),
                ],
                db_index=True,
                default="TO_DO",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.DeleteModel(
            name="ProgressState",
        ),
    ]
