# Generated by Django 4.2.20 on 2025-04-22 10:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tasks", "0021_taskworkflow_eif_date_taskworkflow_policy_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="automation_class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "workbaskets.models.CreateWorkBasketAutomation",
                        "Create workbasket",
                    ),
                ],
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
    ]
