# Generated by Django 4.2.17 on 2025-02-25 15:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_taskworkflow_eif_date_taskworkflow_policy_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskworkflow",
            name="policy_contact",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
