# Generated by Django 4.2.18 on 2025-04-17 13:33

import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_tasktemplate_automation_class_name_automation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress_state",
            field=django_fsm.FSMField(
                choices=[
                    ("TO_DO", "To do"),
                    ("IN_PROGRESS", "In progress"),
                    ("DONE", "Done"),
                ],
                db_index=True,
                default="TO_DO",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasktemplate",
            name="automation_class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "workbaskets.models.CreateWorkBasketAutomation",
                        "Create workbasket",
                    ),
                ],
                max_length=200,
            ),
        ),
        migrations.DeleteModel(
            name="ProgressState",
        ),
    ]
