# Generated by Django 4.2.20 on 2025-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_alter_task_progress_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tasktemplate",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
