# Generated by Django 4.2.20 on 2025-04-28 16:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_alter_task_progress_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktemplate",
            name="automation_class_name",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "workbaskets.models.CreateWorkBasketAutomation",
                        "Create workbasket",
                    ),
                    (
                        "importer.models.ImportGoodsAutomation",
                        "Import commodity codes",
                    ),
                ],
                max_length=200,
            ),
        ),
    ]
