# Generated by Django 4.2.21 on 2025-05-15 16:49

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workbaskets", "0013_createworkbasketautomation"),
        ("tasks", "0024_alter_tasktemplate_automation_class_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="workbasket",
        ),
        migrations.AddField(
            model_name="taskworkflow",
            name="workbasket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workbaskets.workbasket",
            ),
        ),
    ]
