# Generated by Django 4.2.21 on 2025-05-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0025_remove_task_workbasket_taskworkflow_workbasket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tasktemplate",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
