# Generated by Django 3.0.4 on 2020-07-03 09:01
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations
from django.db import models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("footnotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCode",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "sid",
                    models.PositiveIntegerField(
                        validators=[common.validators.NumericSIDValidator()]
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9][A-Z0-9][A-Z0-9]$"
                            )
                        ],
                    ),
                ),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="AdditionalCodeDescription",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "description_period_sid",
                    models.PositiveIntegerField(
                        validators=[common.validators.NumericSIDValidator()]
                    ),
                ),
                ("description", models.TextField()),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="AdditionalCodeType",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "sid",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Z0-9]$")
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "application_code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Export refund nomenclature"),
                            (1, "Additional codes"),
                            (3, "Meursing additional codes"),
                            (4, "Export refund for processed agricultural goods"),
                        ]
                    ),
                ),
            ],
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.CreateModel(
            name="FootnoteAssociationAdditionalCode",
            fields=[
                (
                    "trackedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.TrackedModel",
                    ),
                ),
                (
                    "valid_between",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "additional_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="additional_codes.AdditionalCode",
                    ),
                ),
                (
                    "associated_footnote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="footnotes.Footnote",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("common.trackedmodel", models.Model),
        ),
        migrations.AddConstraint(
            model_name="additionalcodetype",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_additional_code_types",
            ),
        ),
        migrations.AddField(
            model_name="additionalcodedescription",
            name="described_additional_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="additional_codes.AdditionalCode",
            ),
        ),
        migrations.AddField(
            model_name="additionalcode",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="additional_codes.AdditionalCodeType",
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalcodedescription",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("valid_between", "&&"),
                    ("described_additional_code", "="),
                ],
                name="exclude_overlapping_additional_code_descriptions",
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalcode",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("valid_between", "&&"), ("sid", "=")],
                name="exclude_overlapping_additional_codes",
            ),
        ),
        migrations.AddConstraint(
            model_name="additionalcode",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (django.db.models.functions.text.Lower("valid_between"), "="),
                    ("type", "="),
                    ("code", "="),
                ],
                name="exclude_overlapping_additional_codes_ACN1",
            ),
        ),
    ]
