# Generated by Django 3.0.9 on 2020-08-13 11:13
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0002_update_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcode",
            name="sid",
            field=common.models.NumericSID(),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="description_period_sid",
            field=common.models.NumericSID(),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="description",
            field=common.models.ShortDescription(blank=True, max_length=500, null=True),
        ),
    ]
