# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0003_use_common_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcode",
            name="sid",
            field=common.fields.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="description_period_sid",
            field=common.fields.SignedIntSID(),
        ),
    ]
