# Generated by Django 3.0.10 on 2020-12-01 14:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0004_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcodetype",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcodetype",
            name="exclude_overlapping_additional_code_types",
        ),
    ]
