# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0004_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnoteassociationadditionalcode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
