# Generated by Django 3.1 on 2021-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0004_auto_20210419_1247"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalcodedescription",
            old_name="described_additional_code",
            new_name="described_additionalcode",
        ),
    ]
