# Generated by Django 3.0.10 on 2020-12-07 16:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0005_auto_20201201_1454"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcode",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcode",
            name="exclude_overlapping_additional_codes",
        ),
        migrations.RemoveConstraint(
            model_name="additionalcode",
            name="exclude_overlapping_additional_codes_ACN1",
        ),
    ]
