# Generated by Django 3.0.11 on 2020-11-17 14:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0005_auto_20201117_0926"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcodedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcodedescription",
            name="exclude_overlapping_additional_code_descriptions",
        ),
    ]
