# Generated by Django 3.1 on 2020-12-29 11:47
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0006_auto_20201207_1621"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcodedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcodedescription",
            name="exclude_overlapping_additional_code_descriptions",
        ),
        migrations.AlterField(
            model_name="additionalcode",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]$")],
            ),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="footnoteassociationadditionalcode",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
    ]
