# Generated by Django 3.0.11 on 2020-11-18 18:56
import django.core.validators
from django.db import migrations
from django.db import models

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0006_auto_20201117_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcode",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="description_period_sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="sid",
            field=models.CharField(
                db_index=True,
                max_length=1,
                validators=[django.core.validators.RegexValidator("^[A-Z0-9]$")],
            ),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="footnoteassociationadditionalcode",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
    ]
