# Generated by Django 3.0.10 on 2020-12-07 20:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0006_auto_20201207_1621"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcodedescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcodedescription",
            name="exclude_overlapping_additional_code_descriptions",
        ),
    ]
