# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0007_auto_20201207_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcode",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="additionalcodedescription",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="additionalcodetype",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="footnoteassociationadditionalcode",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
