# Generated by Django 3.1 on 2020-12-12 12:13
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("additional_codes", "0007_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcodetype",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="additionalcode",
            name="exclude_overlapping_additional_codes",
        ),
        migrations.RemoveConstraint(
            model_name="additionalcodetype",
            name="exclude_overlapping_additional_code_types",
        ),
    ]
