name: Setup Python
description: |
  Install Python and dependencies based on
  repository runtime.txt and requirements.txt
runs:
  using: composite
  steps:
    - name: Detect runtime version
      id: runtimes
      shell: bash
      run: echo "::set-output name=python-version::$(cat ./runtime.txt | grep -Eo '[0-9]+\.[0-9]+')"

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ steps.runtimes.outputs.python-version }}

    - name: Restore dependencies from cache
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
