# Generated by Django 3.1.14 on 2023-02-01 19:27

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadingreport",
            name="file_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="loadingreport",
            name="comments",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="loading_report",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packagedworkbaskets",
                to="publishing.loadingreport",
            ),
        ),
    ]
