# Generated by Django 3.1.14 on 2022-12-12 17:54

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="processing_state",
            field=django_fsm.FSMField(
                choices=[
                    ("AWAITING_PROCESSING", "Reviewed and awaiting processing"),
                    ("CURRENTLY_PROCESSING", "Currently processing"),
                    ("SUCCESSFULLY_PROCESSED", "Successfully processed"),
                    ("FAILED_PROCESSING", "Failed processing"),
                    ("ABANDONED", "Abandoned"),
                ],
                db_index=True,
                default="AWAITING_PROCESSING",
                editable=False,
                max_length=50,
                protected=True,
            ),
        ),
    ]
