# Generated by Django 3.1.14 on 2022-11-18 18:46

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="position",
            field=models.SmallIntegerField(
                db_index=True,
                editable=False,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
