# Generated by Django 3.1.14 on 2023-01-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_state",
                    models.CharField(
                        choices=[
                            ("PAUSED", "Envelope processing is paused"),
                            (
                                "UNPAUSED",
                                "Envelope processing is unpaused and may proceed",
                            ),
                        ],
                        default="PAUSED",
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
    ]
