# Generated by Django 3.1.14 on 2023-01-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagedworkbasket",
            options={
                "ordering": ["position"],
                "verbose_name_plural": "packaged workbaskets",
            },
        ),
    ]
