# Generated by Django 3.1.14 on 2023-01-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20230127_1615"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagedworkbasket",
            options={
                "ordering": ["position"],
                "permissions": [
                    ("manage_packaging_queue", "Can manage the packaging queue"),
                    (
                        "consume_from_packaging_queue",
                        "Can consume from the packaging queue",
                    ),
                ],
                "verbose_name_plural": "packaged workbaskets",
            },
        ),
    ]
