# Generated by Django 3.1.14 on 2023-02-06 15:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0002_auto_20230201_1927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadingreport",
            name="comments",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
