# Generated by Django 3.1.14 on 2022-11-21 09:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20221118_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="position",
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
    ]
