# Generated by Django 3.1.14 on 2023-01-27 18:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20230127_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="loading_report",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packagedworkbaskets",
                to="publishing.loadingreport",
            ),
        ),
    ]
