# Generated by Django 3.1.14 on 2023-01-23 12:00

import django.db.models.deletion
from django.db import migrations
from django.db import models

import publishing.models
import publishing.storages


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20230119_1036"),
    ]

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("envelope_id", publishing.models.EnvelopeId()),
                (
                    "xml_file",
                    models.FileField(
                        default="",
                        storage=publishing.storages.EnvelopeStorage,
                        upload_to="",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ("envelope_id",),
            },
        ),
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="envelope",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packagedworkbaskets",
                to="publishing.envelope",
            ),
        ),
    ]
