# Generated by Django 3.1.14 on 2022-12-16 15:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20221212_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadingreport",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loadingreport",
            name="report_file",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="packagedworkbasket",
            name="currently_processing_start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
