# Generated by Django 3.2.18 on 2023-04-25 08:53

import django_chunk_upload_handlers.clam_av
from django.db import migrations
from django.db import models

import publishing.storages


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0002_auto_20230207_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadingreport",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=publishing.storages.LoadingReportStorage,
                upload_to="",
                validators=[
                    django_chunk_upload_handlers.clam_av.validate_virus_check_result,
                ],
            ),
        ),
    ]
