# Generated by Django 3.1.14 on 2022-12-16 15:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_auto_20221212_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="eif",
            field=models.DateField(
                blank=True,
                help_text="For Example, 27 3 2008",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="embargo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="packagedworkbasket",
            name="jira_url",
            field=models.URLField(help_text="Insert Tops Jira ticket link"),
        ),
    ]
