# Generated by Django 3.1.14 on 2023-01-30 10:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0003_auto_20230128_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="published_to_tariffs_api",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
