# Generated by Django 3.1.14 on 2022-12-19 16:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0003_auto_20221216_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadingreport",
            name="comment",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="loadingreport",
            name="report_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
