# Generated by Django 3.2.18 on 2023-05-05 14:10

import django.db.models.deletion
import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0003_alter_loadingreport_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrownDependenciesEnvelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publishing_state",
                    django_fsm.FSMField(
                        choices=[
                            ("AWAITING_PUBLISHING", "Awaiting publishing"),
                            ("CURRENTLY_PUBLISHING", "Currently publishing"),
                            ("SUCCESSFULLY_PUBLISHED", "Successfully published"),
                            ("FAILED_PUBLISHING", "Failed publishing"),
                        ],
                        db_index=True,
                        default="AWAITING_PUBLISHING",
                        editable=False,
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.AddField(
            model_name="packagedworkbasket",
            name="crown_dependencies_envelope",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packagedworkbaskets",
                to="publishing.crowndependenciesenvelope",
            ),
        ),
    ]
