# Generated by Django 3.1.14 on 2022-12-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0004_auto_20221219_1605"),
        ("publishing", "0003_auto_20221216_1512"),
    ]

    operations = []
