# Generated by Django 3.2.18 on 2023-05-30 11:22

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0004_auto_20230505_1510"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tapapienvelope",
            old_name="production_published",
            new_name="published",
        ),
        migrations.RemoveField(
            model_name="tapapienvelope",
            name="staging_published",
        ),
        migrations.AlterField(
            model_name="tapapienvelope",
            name="publishing_state",
            field=django_fsm.FSMField(
                choices=[
                    ("AWAITING_PUBLISHING", "Awaiting publishing"),
                    ("CURRENTLY_PUBLISHING", "Currently publishing"),
                    ("SUCCESSFULLY_PUBLISHED", "Successfully published"),
                    ("FAILED_PUBLISHING", "Failed publishing"),
                ],
                db_index=True,
                default="AWAITING_PUBLISHING",
                editable=False,
                max_length=50,
                protected=True,
            ),
        ),
    ]
