# Generated by Django 3.2.18 on 2023-06-01 15:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0004_add_crown_dependencies_envelope"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrownDependenciesPublishingTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
