# Generated by Django 3.1.14 on 2023-01-30 10:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0004_envelope_published_to_tariffs_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envelope",
            name="deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
