# Generated by Django 3.2.18 on 2023-05-31 14:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0004_add_crown_dependencies_envelope"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowndependenciesenvelope",
            name="publishing_task_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
