# Generated by Django 3.2.18 on 2023-06-02 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publishing", "0005_crowndependenciespublishingtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrownDependenciesPublishingOperationalStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publishing_state",
                    models.CharField(
                        choices=[
                            ("PAUSED", "Envelope publishing is paused"),
                            (
                                "UNPAUSED",
                                "Envelope publishing is unpaused and may proceed",
                            ),
                        ],
                        default="PAUSED",
                        max_length=8,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "crown dependencies publishing operational statuses",
                "ordering": ["pk"],
            },
        ),
    ]
