# Generated by Django 3.2.18 on 2023-05-30 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0005_auto_20230530_1222"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TAPApiEnvelope",
            new_name="CrownDependenciesEnvelope",
        ),
    ]
