# Generated by Django 3.2.18 on 2023-06-05 15:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0006_crowndependenciespublishingoperationalstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowndependenciespublishingtask",
            name="error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
