# Generated by Django 3.2.18 on 2023-07-06 08:17

import django.db.models.deletion
from django.db import migrations
from django.db import models


def add_packaged_workbasket_to_loading_report(apps, schema_editor):
    """Migrate existing associations by adding packaged workbaskets that have a
    loading report to the newly-created `packaged_workbasket` field on
    `LoadingReport` before removing `loading_report` field from
    `PackagedWorkBasket`."""
    PackagedWorkBasket = apps.get_model("publishing", "PackagedWorkBasket")
    for packaged_workbasket in PackagedWorkBasket.objects.all():
        loading_report = packaged_workbasket.loading_report
        if loading_report:
            loading_report.packaged_workbasket = packaged_workbasket
            loading_report.save()


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0007_crowndependenciespublishingtask_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadingreport",
            name="packaged_workbasket",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loadingreports",
                to="publishing.packagedworkbasket",
            ),
        ),
        migrations.RunPython(add_packaged_workbasket_to_loading_report),
        migrations.RemoveField(
            model_name="packagedworkbasket",
            name="loading_report",
        ),
    ]
