# Generated by Django 3.2.19 on 2023-10-27 13:45

from django.db import migrations
from django.db import models


def envelope_validation_state_data_setup(apps, schema_editor):
    """Forward data migration used to set the newly added `validation_state`
    attribute with a value of SUCCESSFULLY_VALIDATED on successfully processed
    (published) envelopes, reasonably assuming that all successfully processed
    envelopes have also been successfully validated."""

    Envelope = apps.get_model("publishing", "Envelope")
    Envelope.objects.filter(
        packagedworkbaskets__processing_state="SUCCESSFULLY_PROCESSED",
    ).update(validation_state=2)


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0008_loadingreport_packaged_workbasket"),
    ]

    operations = [
        # Schema migration.
        migrations.AddField(
            model_name="envelope",
            name="validation_state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Not validated"),
                    (2, "Successfully validated"),
                    (3, "Document invalid"),
                    (4, "TARIC data assertion error"),
                ],
                default=1,
            ),
        ),
        # Data migration.
        migrations.RunPython(
            envelope_validation_state_data_setup,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
