# Generated by Django 3.0.10 on 2020-11-13 17:12
import uuid

import django.db.models.deletion
import storages.backends.s3boto3
from django.db import migrations
from django.db import models

import exporter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("envelope_id", exporter.models.EnvelopeId()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=storages.backends.s3boto3.S3Boto3Storage,
                        upload_to=exporter.models.to_hmrc,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("checksum", models.CharField(editable=False, max_length=32)),
                ("notification_sent", models.DateTimeField(editable=False, null=True)),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exporter.Envelope",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvelopeTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exporter.Envelope",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exporter.Transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="envelope",
            name="transactions",
            field=models.ManyToManyField(
                related_name="envelopes",
                through="exporter.EnvelopeTransaction",
                to="exporter.Transaction",
            ),
        ),
    ]
