# Generated by Django 3.1.6 on 2021-02-19 10:43

from django.db import migrations
from django.db import models

import exporter.models
import exporter.storages


class Migration(migrations.Migration):

    dependencies = [
        ("exporter", "0002_auto_20210218_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                storage=exporter.storages.HMRCStorage,
                upload_to=exporter.models.to_hmrc,
            ),
        ),
    ]
