# Generated by Django 3.1.14 on 2022-01-26 10:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("exporter", "0003_auto_20210219_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
