# Generated by Django 3.2.18 on 2023-05-31 11:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifieduser",
            name="enrol_api_publishing",
            field=models.BooleanField(default=False),
        ),
    ]
