# Generated by Django 3.2.20 on 2023-09-08 07:50

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notifieduser_enrol_api_publishing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified_object_pk", models.IntegerField(default=None, null=True)),
                (
                    "notificaiton_type",
                    models.CharField(
                        choices=[
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31760>",
                                "Goods Report",
                            ),
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31b20>",
                                "Packaging Notify Ready",
                            ),
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31b50>",
                                "Packaging Accepted",
                            ),
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31bb0>",  # /PS-IGNORE
                                "Packaging Rejected",
                            ),
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31c10>",
                                "Publishing Success",
                            ),
                            (
                                "<notifications.models.CustomNotificationChoice object at 0xffffafc31c70>",
                                "Publishing Failed",
                            ),
                        ],
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="template_id",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="response_ids",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notifieduser",
            name="enrol_goods_report",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CrownDependenciesEnvelopeFailedNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="CrownDependenciesEnvelopeSuccessNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="EnvelopeAcceptedNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="EnvelopeReadyForProcessingNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="EnvelopeRejectedNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="GoodsSuccessfulImportNotification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.notification",),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="notifications.notification",
            ),
        ),
    ]
