# Generated by Django 3.2.20 on 2023-08-11 15:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0002_notifieduser_enrol_api_publishing"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="response_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notifieduser",
            name="enrol_goods_report",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("goods_report", "Goods Report"),
                            ("packaging", "Packaging"),
                            ("publishing", "Publishing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("attachment_id", models.PositiveIntegerField(null=True)),
                ("template_id", models.CharField(max_length=100)),
                ("personalisation", models.JSONField()),
                (
                    "attachment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        null=True,
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(to="notifications.NotifiedUser"),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="notifications.notification",
            ),
        ),
    ]
