# Generated by Django 3.1 on 2021-02-01 16:39
from django.db import migrations

from common.migration_operations import ConvertTaricDateRange


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0001_initial"),
    ]

    operations = [
        ConvertTaricDateRange("geographicalarea", "valid_between"),
        ConvertTaricDateRange("geographicalareadescription", "valid_between"),
        ConvertTaricDateRange("geographicalmembership", "valid_between"),
    ]
