# Generated by Django 3.0.10 on 2020-10-27 10:22
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0004_auto_20200924_1358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalarea",
            name="sid",
            field=common.models.SignedIntSID(),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="sid",
            field=common.models.SignedIntSID(),
        ),
    ]
