# Generated by Django 3.1.8 on 2021-06-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0004_validity_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geographicalareadescription",
            old_name="area",
            new_name="described_geographicalarea",
        ),
    ]
