# Generated by Django 4.2.10 on 2024-02-23 11:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_areas", "0005_rename_described_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalarea",
            name="memberships",
            field=models.ManyToManyField(
                through="geo_areas.GeographicalMembership",
                to="geo_areas.geographicalarea",
            ),
        ),
    ]
