# Generated by Django 3.0.10 on 2020-12-01 00:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0005_auto_20201027_1022"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="geographicalarea",
            name="exclude_overlapping_areas",
        ),
    ]
