# Generated by Django 3.0.11 on 2020-11-17 09:26
from django.db import migrations

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0005_auto_20201027_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalarea",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="geographicalmembership",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(),
        ),
    ]
