# Generated by Django 3.0.10 on 2020-12-10 09:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0006_auto_20201201_0002"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geographicalarea",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="geographicalareadescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="geographicalmembership",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="geographicalarea",
            name="only_groups_have_parents",
        ),
        migrations.RemoveConstraint(
            model_name="geographicalareadescription",
            name="exclude_overlapping_area_descriptions",
        ),
        migrations.RemoveConstraint(
            model_name="geographicalmembership",
            name="exclude_overlapping_memberships",
        ),
    ]
