# Generated by Django 3.0.11 on 2020-11-17 14:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0006_auto_20201117_0926"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geographicalareadescription",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="geographicalareadescription",
            name="exclude_overlapping_area_descriptions",
        ),
    ]
