# Generated by Django 3.1 on 2020-12-26 10:01
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0007_auto_20201210_0942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="geo_areas.geographicalarea",
            ),
        ),
    ]
