# Generated by Django 3.1 on 2020-12-29 11:47
import django.db.models.deletion
from django.db import migrations
from django.db import models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0007_auto_20201210_0942"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geographicalarea",
            options={},
        ),
        migrations.AlterField(
            model_name="geographicalarea",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="geo_areas.geographicalarea",
            ),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalmembership",
            name="valid_between",
            field=common.fields.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="geographicalarea",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("area_code", 1), ("parent__isnull", True), _connector="OR"
                ),
                name="only_groups_have_parents",
            ),
        ),
    ]
