# Generated by Django 3.0.11 on 2020-11-18 18:56
from django.db import migrations

import common.fields
import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0007_auto_20201117_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalarea",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalarea",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="sid",
            field=common.fields.SignedIntSID(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="geographicalmembership",
            name="valid_between",
            field=common.models.TaricDateTimeRangeField(db_index=True),
        ),
    ]
