# Generated by Django 3.1 on 2020-12-10 19:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0008_auto_20201118_1856"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geographicalmembership",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="geographicalmembership",
            name="exclude_overlapping_memberships",
        ),
    ]
