# Generated by Django 3.1 on 2020-12-27 10:51
from django.db import migrations

import common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0008_auto_20201226_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geographicalarea",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="geographicalareadescription",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
        migrations.AlterField(
            model_name="geographicalmembership",
            name="valid_between",
            field=common.models.fields.TaricDateTimeRangeField(),
        ),
    ]
