# Generated by Django 3.1 on 2020-12-11 07:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_areas", "0009_auto_20201210_1948"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="geographicalarea",
            name="exclude_overlapping_areas",
        ),
    ]
